import { clearSession, setSession } from '../lib/auth';
import type { components } from './schema';

const API = '/api/v1';

/** The response shapes the API's OpenAPI document names, generated by `npm run openapi:generate`.
 * Every type below that mirrors a response DTO derives from here instead of restating its fields,
 * so a field the API adds, drops, or renames surfaces as a type error in this root. Shapes the
 * document does not name — the endpoints returning them document an example rather than a
 * response type — stay hand-written below and carry no such guarantee. */
type Schemas = components['schemas'];

/** `Omit` restricted to keys the source type actually has. The built-in accepts any string, so a
 * field the API renames would fall out of an omit list unnoticed and be re-added by the local
 * override beside it — reinstating the drift the generated types exist to catch. */
type StrictOmit<T, K extends keyof T> = Omit<T, K>;

export type Me = Schemas['MeResponseDto'];
export type UserRole = Me['role'];
export type AuthToken = Schemas['AuthTokenResponseDto'];

export class ApiError extends Error {
  status: number;

  constructor(status: number, message: string) {
    super(message);
    this.status = status;
  }
}

// The single wording for an unreachable server, reached by every call site through
// `TransportError` rather than restated per page.
const TRANSPORT_ERROR_MESSAGE = 'Could not reach the server. Check your connection and try again.';

/** Thrown when `fetch` itself never produces an HTTP response — a dropped connection, DNS
 * failure, or the request's own timeout. `status` is `0`, the sentinel for "no server status to
 * report," distinguishing this from any status a server actually returned. */
export class TransportError extends ApiError {
  constructor() {
    super(0, TRANSPORT_ERROR_MESSAGE);
  }
}

// Bounds an ordinary JSON call: generous enough that a slow-but-working request still finishes,
// short enough that a genuinely dead connection surfaces as a transport error instead of hanging
// the UI forever. Model synthesis itself runs on the answer-question workflow and is polled or
// streamed separately — nothing awaits it inline through this helper.
const DEFAULT_TIMEOUT_MS = 30_000;

// A document upload carries a full file body over what may be a much slower link than the JSON
// calls above; the default budget would abort a large file partway through.
const UPLOAD_TIMEOUT_MS = 120_000;

async function readErrorMessage(res: Response): Promise<string> {
  try {
    const text = await res.text();
    if (!text) return res.statusText || `HTTP ${res.status}`;
    const body = JSON.parse(text) as unknown;
    if (
      body !== null &&
      typeof body === 'object' &&
      'message' in body &&
      typeof (body as Record<string, unknown>).message === 'string'
    ) {
      return (body as Record<string, unknown>).message as string;
    }
  } catch {}
  return res.statusText || `HTTP ${res.status}`;
}

async function request<T>(path: string, init?: RequestInit): Promise<T> {
  const isFormData = init?.body instanceof FormData;
  const headers: Record<string, string> = {
    // A FormData body needs the browser to set its own multipart boundary; a fixed
    // 'application/json' header here would make the server unable to parse the upload.
    ...(isFormData ? {} : { 'Content-Type': 'application/json' }),
    ...(init?.headers as Record<string, string> | undefined),
  };

  const timeoutController = new AbortController();
  const timeoutId = setTimeout(
    () => timeoutController.abort(),
    isFormData ? UPLOAD_TIMEOUT_MS : DEFAULT_TIMEOUT_MS,
  );
  // No caller passes its own signal today; composing rather than overwriting keeps that case
  // correct if one ever does.
  const signal = init?.signal
    ? AbortSignal.any([init.signal, timeoutController.signal])
    : timeoutController.signal;

  // The timer spans the body read as well as the response, not just `fetch`: `fetch` settles as
  // soon as the headers arrive, so a server that sends headers and then stalls mid-body would hold
  // the request open indefinitely if the timeout were cleared at that point.
  try {
    // The credential is an HttpOnly cookie the SPA never handles itself; 'same-origin' is what
    // makes the browser attach it.
    const res = await fetch(`${API}${path}`, {
      ...init,
      headers,
      credentials: 'same-origin',
      signal,
    });

    if (res.status === 401 && !path.startsWith('/auth/')) {
      window.location.assign('/login');
      throw new ApiError(401, 'Unauthorized');
    }

    if (!res.ok) {
      throw new ApiError(res.status, await readErrorMessage(res));
    }

    if (res.status === 204) {
      return undefined as T;
    }

    const text = await res.text();
    if (!text) return undefined as T;

    try {
      return JSON.parse(text) as T;
    } catch {
      // A 2xx whose body is not JSON means something answered in the API's place — a proxy landing
      // on the wrong upstream, or a captive portal. Raising `ApiError` holds the guarantee every
      // call site relies on, that this module throws `ApiError` and nothing else; the raw
      // `SyntaxError` would put "Unexpected token '<'" in front of the user instead.
      throw new ApiError(res.status, 'The server sent a response this app could not read.');
    }
  } catch (err) {
    // Recognized as "no complete response arrived": this helper's own timeout, whether it fired
    // against the connection or against a stalled body, or the TypeError a browser throws for a
    // dropped connection, blocked CORS request, or DNS failure. `ApiError` passes through — a
    // server that answered is not a transport failure — and so does anything unrecognized, because
    // swallowing it into a generic message would hide a real defect rather than surface it.
    if (err instanceof ApiError) throw err;
    if (timeoutController.signal.aborted || err instanceof TypeError) {
      throw new TransportError();
    }
    throw err;
  } finally {
    clearTimeout(timeoutId);
  }
}

function jsonBody(data: unknown): RequestInit {
  return { body: JSON.stringify(data) };
}

export function register(email: string, password: string): Promise<Me> {
  return request<Me>('/auth/register', { method: 'POST', ...jsonBody({ email, password }) });
}

// The invitation dictates the account's email, tenant and role, so redemption collects only a
// password — the server ignores any email the caller might otherwise supply.
export function registerWithInvitation(password: string, invitationToken: string): Promise<Me> {
  return request<Me>('/auth/register', {
    method: 'POST',
    ...jsonBody({ password, invitationToken }),
  });
}

export async function login(email: string, password: string): Promise<AuthToken> {
  const result = await request<AuthToken>('/auth/login', {
    method: 'POST',
    ...jsonBody({ email, password }),
  });
  setSession(result.user);
  return result;
}

export async function logout(): Promise<void> {
  // Client-side logout must not depend on the server's answer: a CSRF rejection, a 500, or a
  // dropped connection must not leave the local session cache believing the user is still
  // authenticated just because the request that says otherwise never arrived.
  try {
    await request<void>('/auth/logout', { method: 'POST' });
  } finally {
    clearSession();
  }
}

export function getMe(): Promise<Me> {
  return request<Me>('/auth/me');
}

// ── Documents ────────────────────────────────────────────────────────────

export type DocumentVersion = Schemas['DocumentVersionResponseDto'];
export type DocumentVersionIngestionStatus = DocumentVersion['ingestionStatus'];

// Named `EvidenceDocument`, not `Document` — the latter shadows the DOM global that the rest
// of the SPA (and jsdom in tests) relies on.
export type EvidenceDocument = Schemas['DocumentResponseDto'];
export type DocumentSourceKind = EvidenceDocument['sourceKind'];
export type DocumentWithVersions = Schemas['DocumentWithVersionsResponseDto'];

/** The envelope every paginated endpoint returns. Hand-written: the API declares these responses
 * with an example rather than a response type, so the OpenAPI document names no schema for the
 * envelope or for its element types. */
export interface WithCount<T> {
  docs: T[];
  count: number;
}

export function uploadDocument(
  file: File,
  options?: {
    documentId?: string;
    title?: string;
    // Ignored by the server when documentId is set — a new version never changes its document's
    // class. Never 'unclassified': that is what omitting this field already means.
    sourceClass?: DocumentSourceClass;
  },
): Promise<EvidenceDocument> {
  const formData = new FormData();
  formData.append('file', file);
  if (options?.documentId) formData.append('documentId', options.documentId);
  else formData.append('title', options?.title?.trim() || file.name);
  if (options?.sourceClass) formData.append('sourceClass', options.sourceClass);
  return request<EvidenceDocument>('/documents', { method: 'POST', body: formData });
}

export function listDocuments(params?: {
  skip?: number;
  limit?: number;
  // Filters to documents whose CURRENT version has this ingestionStatus — 'failed' and
  // 'needs-ocr' are the corpus-health use cases. An older failed version superseded by a
  // completed one does not match.
  ingestionStatus?: DocumentVersionIngestionStatus;
}): Promise<WithCount<EvidenceDocument>> {
  const query = new URLSearchParams();
  if (params?.skip !== undefined) query.set('skip', String(params.skip));
  if (params?.limit !== undefined) query.set('limit', String(params.limit));
  if (params?.ingestionStatus !== undefined) query.set('ingestionStatus', params.ingestionStatus);
  const qs = query.toString();
  return request<WithCount<EvidenceDocument>>(`/documents${qs ? `?${qs}` : ''}`);
}

export function getDocumentById(id: string): Promise<DocumentWithVersions> {
  return request<DocumentWithVersions>(`/documents/${id}`);
}

// Admin-only, and irreversible: the server cascades to versions, chunks, facts and stored bytes.
// Answers that already cited this document keep their citations — see documents.service.ts.
export async function deleteDocument(id: string): Promise<void> {
  await request<void>(`/documents/${id}`, { method: 'DELETE' });
}

// A plain URL builder, not a `request<T>()` call: the browser fetches this href directly to
// drive a file download, so there is no JSON body for `request<T>()` to parse.
export function documentVersionContentUrl(versionId: string): string {
  return `${API}/documents/versions/${versionId}/content`;
}

// A plain URL builder, not a `request<T>()` call — a browser-native EventSource consumes this
// href directly, so there is no JSON body for `request<T>()` to parse. Takes the same `skip`/
// `limit` as `listDocuments` — the stream mirrors whichever page the caller is on, so the two
// must always agree on which documents to show.
export function documentEventsUrl(params?: { skip?: number; limit?: number }): string {
  const query = new URLSearchParams();
  if (params?.skip !== undefined) query.set('skip', String(params.skip));
  if (params?.limit !== undefined) query.set('limit', String(params.limit));
  const qs = query.toString();
  return `${API}/documents/events${qs ? `?${qs}` : ''}`;
}

// What a citation actually points at — the stored evidence_chunks, not a re-parse of the source
// document. Chunk granularity may span pages, ~12% overlap means adjacent chunks repeat some
// text, and elements quarantined at ingestion are absent entirely: not a faithful page render.
export type EvidenceChunkView = StrictOmit<Schemas['EvidenceChunkResponseDto'], 'locator'> & {
  // The document types a locator as a bare object: `Locator` is a discriminated union the API
  // describes in prose, and OpenAPI carries no schema for it.
  locator: Locator;
};

export function listVersionChunks(versionId: string): Promise<WithCount<EvidenceChunkView>> {
  return request<WithCount<EvidenceChunkView>>(`/documents/versions/${versionId}/chunks`);
}

// ── Questions & answers ─────────────────────────────────────────────────

export type AnswerRunStatus = Schemas['AnswerResponseDto']['runStatus'];

export type Locator =
  | {
      kind: 'pdf-page';
      extractorVersion: string;
      page: number;
      boundingBox?: { x: number; y: number; width: number; height: number };
    }
  | {
      kind: 'docx-paragraph';
      extractorVersion: string;
      paragraphIndex: number;
      headingPath: string[];
    }
  | { kind: 'xlsx-region'; extractorVersion: string; sheetName: string; range: string }
  | { kind: 'xlsx-cell'; extractorVersion: string; sheetName: string; cell: string }
  | { kind: 'text-block'; extractorVersion: string; blockIndex: number; headingPath: string[] }
  | { kind: 'pptx-slide'; extractorVersion: string; slide: number };

export interface Citation {
  docVersionId: string;
  sha256: string;
  chunkId: string;
  locator: Locator;
  quote: string;
}

export interface Claim {
  statement: string;
  citations: Citation[];
}

export interface ConflictingValue {
  value: number;
  unit: string;
  sourceChunkId: string;
}

export interface ConflictingFactKey {
  entity: string;
  metric: string;
  period: string;
}

export type InsufficientEvidenceReasonCode =
  | 'no_relevant_evidence'
  | 'evidence_does_not_address_question'
  | 'retrieved_evidence_contradicts_itself';

export type AnswerOutcome =
  | { kind: 'answered'; claims: Claim[] }
  // `reasonCode` is present only for a model-authored abstention (absent on legacy answers and on
  // the grounding gate's own degraded insufficient_evidence — see `answer.contract.ts`'s doc
  // comment on the API side). It never changes what is rendered here on its own: the API only ever
  // returns `kind: 'conflicting_evidence'` once it has independently verified the hint.
  | { kind: 'insufficient_evidence'; reason: string; reasonCode?: InsufficientEvidenceReasonCode }
  | { kind: 'conflicting_evidence'; factKey: ConflictingFactKey; values: ConflictingValue[] };

export type DroppedClaim = Schemas['DroppedClaimResponseDto'];
export type VerificationReport = Schemas['VerificationReportResponseDto'];

// `outcome` and `citations` are the two fields the document types as bare objects — both are
// discriminated unions the API describes in prose. Every other field, including whether it is
// optional, comes from the generated schema.
export type Answer = StrictOmit<Schemas['AnswerResponseDto'], 'outcome' | 'citations'> & {
  // Present only once runStatus is 'completed' — never render this as a final outcome before
  // then (see qa.controller.ts / answer.response.dto.ts).
  outcome?: AnswerOutcome;
  citations: Citation[];
};

export type StartQuestionResult = Schemas['StartQuestionResponseDto'];

export function startQuestion(questionText: string): Promise<StartQuestionResult> {
  return request<StartQuestionResult>('/questions', {
    method: 'POST',
    ...jsonBody({ questionText }),
  });
}

export function getAnswerById(id: string): Promise<Answer> {
  return request<Answer>(`/answers/${id}`);
}

// Three independent optional filters, so this one builds its query with
// URLSearchParams rather than the ad-hoc template literals above.
export function listAnswers(params?: {
  skip?: number;
  limit?: number;
  runStatus?: AnswerRunStatus;
}): Promise<WithCount<Answer>> {
  const query = new URLSearchParams();
  if (params?.skip !== undefined) query.set('skip', String(params.skip));
  if (params?.limit !== undefined) query.set('limit', String(params.limit));
  if (params?.runStatus) query.set('runStatus', params.runStatus);
  const qs = query.toString();
  return request<WithCount<Answer>>(`/answers${qs ? `?${qs}` : ''}`);
}

// A plain URL builder, not a `request<T>()` call — a browser-native EventSource consumes this
// href directly, so there is no JSON body for `request<T>()` to parse.
export function answerEventsUrl(id: string): string {
  return `${API}/answers/${id}/events`;
}

// ── Retrieval ────────────────────────────────────────────────────────────

// What `search_evidence` returns — the retrieved chunk itself, not a relevance score, because
// the API does not return one.
export interface RetrievedChunkView {
  chunkId: string;
  docVersionId: string;
  sha256: string;
  text: string;
  locator: Locator;
}

export function searchEvidence(query: string): Promise<WithCount<RetrievedChunkView>> {
  return request<WithCount<RetrievedChunkView>>(
    `/retrieval/search?query=${encodeURIComponent(query)}`,
  );
}

// ── Conflicts ────────────────────────────────────────────────────────────

export type ConflictStatus = 'open' | 'resolved' | 'dismissed';

export interface ConflictValue {
  factId: string;
  value: number;
  unit: string;
  sourceChunkId: string;
  documentVersionId: string;
  locator: Locator;
  // True when documentVersionId currently carries withdrawnAt — the source file behind this side
  // of the disagreement is no longer at its source. The conflict itself stays open regardless.
  withdrawn: boolean;
}

export type ConflictRuleFired = 'authority' | 'recency' | 'none';

export interface Conflict {
  id: string;
  factKey: ConflictingFactKey;
  factIds: string[];
  values: ConflictValue[];
  magnitude: number;
  status: ConflictStatus;
  createdAt: string;
  // True when one or more factIds no longer resolve to an ExtractedFact — the document that
  // produced them was deleted. proposedWinnerFactId, ruleFired and explanation are all absent
  // then: no survivorship policy runs over a fact set already known to be incomplete.
  unscorable: boolean;
  unscorableReason?: string;
  proposedWinnerFactId?: string;
  ruleFired?: ConflictRuleFired;
  explanation?: string;
}

export function listConflicts(params?: {
  skip?: number;
  limit?: number;
  status?: ConflictStatus;
}): Promise<WithCount<Conflict>> {
  const query = new URLSearchParams();
  if (params?.skip !== undefined) query.set('skip', String(params.skip));
  if (params?.limit !== undefined) query.set('limit', String(params.limit));
  if (params?.status) query.set('status', params.status);
  const qs = query.toString();
  return request<WithCount<Conflict>>(`/conflicts${qs ? `?${qs}` : ''}`);
}

export function requestConflictResolution(
  conflictId: string,
  winningFactId: string,
): Promise<WorkflowRun> {
  return request<WorkflowRun>(`/conflicts/${conflictId}/resolution-requests`, {
    method: 'POST',
    ...jsonBody({ winningFactId }),
  });
}

// ── Approvals ────────────────────────────────────────────────────────────

export type ApprovalState = 'pending' | 'approved' | 'rejected' | 'timed_out';
export type ApprovalDecision = 'approved' | 'rejected';

export interface ApprovalSubject {
  entityType: string;
  entityId: string;
}

export interface Approval {
  id: string;
  subject: ApprovalSubject;
  action: string;
  summary: string;
  requestedBy?: string;
  // Underlying Temporal workflow id, present when this approval gates a workflow (matches
  // WorkflowRun.workflowId) — absent for an approval created outside one.
  workflowId?: string;
  state: ApprovalState;
  decidedBy?: string;
  decidedAt?: string;
  decisionReason?: string;
  createdAt: string;
}

export function listApprovals(params?: {
  skip?: number;
  limit?: number;
  state?: ApprovalState;
}): Promise<WithCount<Approval>> {
  const query = new URLSearchParams();
  if (params?.skip !== undefined) query.set('skip', String(params.skip));
  if (params?.limit !== undefined) query.set('limit', String(params.limit));
  if (params?.state) query.set('state', params.state);
  const qs = query.toString();
  return request<WithCount<Approval>>(`/approvals${qs ? `?${qs}` : ''}`);
}

export function decideApproval(
  id: string,
  decision: ApprovalDecision,
  reason?: string,
): Promise<Approval> {
  return request<Approval>(`/approvals/${id}/decision`, {
    method: 'POST',
    ...jsonBody(reason ? { decision, reason } : { decision }),
  });
}

// ── Workflow runs ────────────────────────────────────────────────────────

export type WorkflowRunStatus = 'queued' | 'running' | 'completed' | 'failed';

// Only the workflows that record a run row. `answer-question` and `ingest-document-version` run
// without one, so they never appear here. Absent on rows written before the field existed.
// `'rescan-conflicts'` is no longer a workflow this codebase starts; kept for existing rows that
// carry it, since no current code path writes it.
export type WorkflowRunType = 'resolve-conflict' | 'sync-source' | 'rescan-conflicts';

export interface WorkflowRun {
  id: string;
  workflowId: string;
  workflowType?: WorkflowRunType;
  status: WorkflowRunStatus;
  errorMessage?: string;
  createdAt: string;
}

export function getWorkflowRunById(id: string): Promise<WorkflowRun> {
  return request<WorkflowRun>(`/workflow-runs/${id}`);
}

export function listWorkflowRuns(params?: {
  workflowId?: string;
  skip?: number;
  limit?: number;
}): Promise<WithCount<WorkflowRun>> {
  const query = new URLSearchParams();
  if (params?.workflowId) query.set('workflowId', params.workflowId);
  if (params?.skip !== undefined) query.set('skip', String(params.skip));
  if (params?.limit !== undefined) query.set('limit', String(params.limit));
  const qs = query.toString();
  return request<WithCount<WorkflowRun>>(`/workflow-runs${qs ? `?${qs}` : ''}`);
}

// A plain URL builder, not a `request<T>()` call — a browser-native EventSource consumes this
// href directly, so there is no JSON body for `request<T>()` to parse.
export function workflowRunEventsUrl(id: string): string {
  return `${API}/workflow-runs/${id}/events`;
}

// ── Audit events ─────────────────────────────────────────────────────────

export interface AuditEventSubject {
  entityType: string;
  entityId: string;
}

export type AuditEventOrigin = 'api' | 'mcp';

export interface AuditEventView {
  id: string;
  actor: string;
  action: string;
  subject: AuditEventSubject;
  timestamp: string;
  correlationId: string;
  createdAt: string;
  origin: AuditEventOrigin;
  toolName?: string;
  refusalReason?: string;
  // Written only on 'sources.class_drift_applied' — the count of documents the remedy rewrote.
  // Absent on every other action.
  modifiedCount?: number;
}

// Five independent optional filters, so this one builds its query with
// URLSearchParams rather than the ad-hoc template literals above.
export function listAuditEvents(params?: {
  skip?: number;
  limit?: number;
  action?: string;
  entityType?: string;
  entityId?: string;
  origin?: AuditEventOrigin;
  refusalReason?: string;
}): Promise<WithCount<AuditEventView>> {
  const query = new URLSearchParams();
  if (params?.skip !== undefined) query.set('skip', String(params.skip));
  if (params?.limit !== undefined) query.set('limit', String(params.limit));
  if (params?.action) query.set('action', params.action);
  if (params?.entityType) query.set('entityType', params.entityType);
  if (params?.entityId) query.set('entityId', params.entityId);
  if (params?.origin) query.set('origin', params.origin);
  if (params?.refusalReason) query.set('refusalReason', params.refusalReason);
  const qs = query.toString();
  return request<WithCount<AuditEventView>>(`/audit-events${qs ? `?${qs}` : ''}`);
}

// ── Sources ──────────────────────────────────────────────────────────────

export type SourceWithFileStates = Schemas['SourceWithFileStatesResponseDto'];

// The list and single-source endpoints return the same row without its per-file state; the
// document names only the detail shape, so the list shape derives from it.
export type Source = StrictOmit<SourceWithFileStates, 'fileStates'>;

export type SourceKind = Source['kind'];
export type SourceConnectivity = Source['connectivity'];
export type SourceReachability = Source['reachability'];

export type SourceFileState = Schemas['SourceFileStateResponseDto'];
export type SourceFileStateStatus = SourceFileState['status'];

export function createSource(input: {
  name: string;
  kind: SourceKind;
  path: string;
  // Required — its absence is the gap an estate's inventory pass exists to surface, so it is
  // never inferred or defaulted.
  owner: string;
  intervalMs?: number;
  enabled?: boolean;
  connectivity?: SourceConnectivity;
  reachability?: SourceReachability;
  tracked?: boolean;
  sourceClass?: DocumentSourceClass;
}): Promise<Source> {
  return request<Source>('/sources', { method: 'POST', ...jsonBody(input) });
}

export function listSources(pagination?: {
  skip?: number;
  limit?: number;
  // Partitions synced ('tracked: true') from inventory-only ('tracked: false') sources into two
  // separately-paged lists — cannot be done by filtering one fetched page client-side, since the
  // pager's count would be the combined total.
  tracked?: boolean;
  // Exact lastSyncStatus to filter by — currently only 'failed' is meaningful.
  lastSyncStatus?: string;
}): Promise<WithCount<Source>> {
  const query = new URLSearchParams();
  if (pagination?.skip !== undefined) query.set('skip', String(pagination.skip));
  if (pagination?.limit !== undefined) query.set('limit', String(pagination.limit));
  if (pagination?.tracked !== undefined) query.set('tracked', String(pagination.tracked));
  if (pagination?.lastSyncStatus !== undefined) {
    query.set('lastSyncStatus', pagination.lastSyncStatus);
  }
  const qs = query.toString();
  return request<WithCount<Source>>(`/sources${qs ? `?${qs}` : ''}`);
}

export function getSourceById(id: string): Promise<SourceWithFileStates> {
  return request<SourceWithFileStates>(`/sources/${id}`);
}

// Every field independently optional and settable — the caller sends only what changed.
export function updateSource(
  id: string,
  input: {
    enabled?: boolean;
    connectivity?: SourceConnectivity;
    reachability?: SourceReachability;
    owner?: string;
    tracked?: boolean;
    sourceClass?: DocumentSourceClass;
  },
): Promise<Source> {
  return request<Source>(`/sources/${id}`, { method: 'PATCH', ...jsonBody(input) });
}

export function requestSourceSync(id: string): Promise<WorkflowRun> {
  return request<WorkflowRun>(`/sources/${id}/sync`, { method: 'POST' });
}

// Authority classification for the survivorship policy. 'unclassified' means nobody has declared
// one — never rendered as an option an uploader can pick, only as the default state.
export type DocumentSourceClass = EvidenceDocument['sourceClass'];

export interface SourceClassDrift {
  previousClass?: DocumentSourceClass;
  count: number;
}

export interface ApplySourceClassDrift {
  modifiedCount: number;
  previousClass?: DocumentSourceClass;
  sourceClass: DocumentSourceClass;
}

export function getSourceClassDrift(id: string): Promise<SourceClassDrift> {
  return request<SourceClassDrift>(`/sources/${id}/class-drift`);
}

export function applySourceClassDrift(id: string): Promise<ApplySourceClassDrift> {
  return request<ApplySourceClassDrift>(`/sources/${id}/class-drift/apply`, { method: 'POST' });
}

// ── API keys ─────────────────────────────────────────────────────────────

export interface ApiKey {
  id: string;
  name: string;
  tokenPrefix: string;
  expiresAt?: string;
  revokedAt?: string;
  // Stamped on every successful verify — the only signal distinguishing a live PAT from an
  // abandoned one. Absent means the key has never authenticated a request.
  lastUsedAt?: string;
  createdAt: string;
}

// The plaintext `token` lives only here — mint is the sole response shape that carries it.
// Nothing persists it beyond this call; a caller that loses this response has lost the token.
export interface MintedApiKey extends ApiKey {
  token: string;
}

export function mintApiKey(name: string, expiresAt?: string): Promise<MintedApiKey> {
  return request<MintedApiKey>('/api-keys', {
    method: 'POST',
    ...jsonBody(expiresAt ? { name, expiresAt } : { name }),
  });
}

export function listApiKeys(params?: {
  skip?: number;
  limit?: number;
}): Promise<WithCount<ApiKey>> {
  const query = new URLSearchParams();
  if (params?.skip !== undefined) query.set('skip', String(params.skip));
  if (params?.limit !== undefined) query.set('limit', String(params.limit));
  const qs = query.toString();
  return request<WithCount<ApiKey>>(`/api-keys${qs ? `?${qs}` : ''}`);
}

export async function revokeApiKey(id: string): Promise<void> {
  await request<void>(`/api-keys/${id}`, { method: 'DELETE' });
}

// Rotates the key's token onto its existing row — same id, name and creation date, a fresh
// plaintext token shown exactly once. The previous token stops working the moment this call
// succeeds; only its hash was ever stored, so there is nothing to fall back to.
export function rotateApiKey(id: string): Promise<MintedApiKey> {
  return request<MintedApiKey>(`/api-keys/${id}/rotate`, { method: 'POST' });
}

// ── Invitations ──────────────────────────────────────────────────────────

export interface Invitation {
  id: string;
  email: string;
  role: UserRole;
  expiresAt: string;
  acceptedAt?: string;
  // Absent means the invitation is still live. A revoked invitation stays in the list rather than
  // being filtered out, so this is what tells the UI its token no longer works.
  revokedAt?: string;
  createdAt: string;
}

// The plaintext `token` lives only here, mirroring `MintedApiKey` — mint is the sole response
// shape that carries it, so nothing else in the SPA ever holds it.
export interface MintedInvitation extends Invitation {
  token: string;
}

export function mintInvitation(email: string, role: UserRole): Promise<MintedInvitation> {
  return request<MintedInvitation>('/invitations', {
    method: 'POST',
    ...jsonBody({ email, role }),
  });
}

export function listInvitations(pagination?: {
  skip?: number;
  limit?: number;
}): Promise<WithCount<Invitation>> {
  const query = new URLSearchParams();
  if (pagination?.skip !== undefined) query.set('skip', String(pagination.skip));
  if (pagination?.limit !== undefined) query.set('limit', String(pagination.limit));
  const qs = query.toString();
  return request<WithCount<Invitation>>(`/invitations${qs ? `?${qs}` : ''}`);
}

// Kills an outstanding invitation inside its live window — both verify and accept refuse its
// token from this point on.
export async function revokeInvitation(id: string): Promise<void> {
  await request<void>(`/invitations/${id}`, { method: 'DELETE' });
}

// Rotates the invitation's token. Only a hash of the previous token was ever stored, so the old
// link stops working the moment this call succeeds — there is no way to recover or reactivate it.
export function resendInvitation(id: string): Promise<MintedInvitation> {
  return request<MintedInvitation>(`/invitations/${id}/resend`, { method: 'POST' });
}

// ── Users ────────────────────────────────────────────────────────────────

export interface User {
  id: string;
  email: string;
  role: UserRole;
  createdAt: string;
}

export function listUsers(pagination?: {
  skip?: number;
  limit?: number;
}): Promise<WithCount<User>> {
  const query = new URLSearchParams();
  if (pagination?.skip !== undefined) query.set('skip', String(pagination.skip));
  if (pagination?.limit !== undefined) query.set('limit', String(pagination.limit));
  const qs = query.toString();
  return request<WithCount<User>>(`/users${qs ? `?${qs}` : ''}`);
}

export function changeUserRole(id: string, role: UserRole): Promise<User> {
  return request<User>(`/users/${id}/role`, { method: 'PATCH', ...jsonBody({ role }) });
}

export async function removeUser(id: string): Promise<void> {
  await request<void>(`/users/${id}`, { method: 'DELETE' });
}

/** Signs the member out of every browser session and disables every API key they hold — raising
 * their session epoch invalidates both, since `ApiKeysService.verify` checks a key's stored epoch
 * against the same `User.tokenVersion` a session cookie is checked against. */
export function revokeUserSessions(id: string): Promise<User> {
  return request<User>(`/users/${id}/revoke-sessions`, { method: 'POST' });
}

// ── Canonical entities ───────────────────────────────────────────────────

/** Whether a harvested alias resolves (`applied`), is recorded but inert (`proposed`), or has been
 * rejected by an operator (`revoked`). A `revoked` alias never returns to `applied`. */
export type HarvestedAliasStatus = 'proposed' | 'applied' | 'revoked';

/** An alias read out of a document's own parenthetical definition — `Northgate Business Park (the
 * "Property")` — with the quote and locator that make it checkable against the source bytes. */
export interface HarvestedAlias {
  alias: string;
  status: HarvestedAliasStatus;
  quote: string;
  locator: Locator;
  documentVersionId: string;
  harvestedAt: string;
}

// Hand-written rather than read from `Schemas` for the `list` shape: `GET /canonical-entities`
// declares its `@ApiResponse` with a description and examples but no `type`, so the OpenAPI
// document names no schema for the paginated form. The single-entity routes (`created`, `updated`,
// the harvested-alias actions) now do declare `type: CanonicalEntityResponseDto` — this interface
// still has to match those by hand, but drift there fails `web`'s typecheck against `schema.ts`
// rather than passing silently the way the whole shape did before.
export interface CanonicalEntity {
  id: string;
  canonicalName: string;
  aliases: string[];
  // Always present; empty until an alias is harvested from a document or proposed by a near-match
  // scan.
  harvestedAliases: HarvestedAlias[];
  createdAt: string;
}

export function listCanonicalEntities(params?: {
  skip?: number;
  limit?: number;
}): Promise<WithCount<CanonicalEntity>> {
  const query = new URLSearchParams();
  if (params?.skip !== undefined) query.set('skip', String(params.skip));
  if (params?.limit !== undefined) query.set('limit', String(params.limit));
  const qs = query.toString();
  return request<WithCount<CanonicalEntity>>(`/canonical-entities${qs ? `?${qs}` : ''}`);
}

export function createCanonicalEntity(input: {
  canonicalName: string;
  aliases?: string[];
}): Promise<CanonicalEntity> {
  return request<CanonicalEntity>('/canonical-entities', { method: 'POST', ...jsonBody(input) });
}

export function updateCanonicalEntity(
  id: string,
  input: { canonicalName?: string; aliases?: string[] },
): Promise<CanonicalEntity> {
  return request<CanonicalEntity>(`/canonical-entities/${id}`, {
    method: 'PATCH',
    ...jsonBody(input),
  });
}

export async function deleteCanonicalEntity(id: string): Promise<void> {
  await request<void>(`/canonical-entities/${id}`, { method: 'DELETE' });
}

/** Scans for unresolved fact entity names that are a suffix-only or punctuation-only near match of
 * a registered row — "Acme Tower, LLC" against a row named "Acme Tower" — and records each as a
 * `proposed` harvested alias on the row it was attributed to. Never applies one itself: a near
 * match is inference, not evidence, so confirming is always a separate, explicit call. */
export function scanNearMatches(): Promise<{ proposed: number }> {
  return request<{ proposed: number }>('/canonical-entities/near-matches/scan', {
    method: 'POST',
  });
}

/** Confirms a `proposed` harvested alias, folding it into resolution — the one-click confirmation
 * for both a document-read alias and a near-match proposal, since both land in the same `proposed`
 * state and this is the only path either can take to `applied`. */
export function applyHarvestedAlias(id: string, alias: string): Promise<CanonicalEntity> {
  return request<CanonicalEntity>(`/canonical-entities/${id}/harvested-aliases/apply`, {
    method: 'POST',
    ...jsonBody({ alias }),
  });
}

/** Rejects a harvested alias — document-read or near-match — so it never resolves. Terminal: a
 * later re-harvest or re-scan that would produce the same alias leaves the rejection standing. */
export function revokeHarvestedAlias(id: string, alias: string): Promise<CanonicalEntity> {
  return request<CanonicalEntity>(`/canonical-entities/${id}/harvested-aliases/revoke`, {
    method: 'POST',
    ...jsonBody({ alias }),
  });
}
