import { clearSession, setSession } from '../lib/auth';
import type { components } from './schema';

const API = '/api/v1';

/** The response shapes the API's OpenAPI document names, generated by `npm run openapi:generate`.
 * Every type below that mirrors a response DTO derives from here instead of restating its fields,
 * so a field the API adds, drops, or renames surfaces as a type error in this root. Shapes the
 * document does not name — the endpoints returning them document an example rather than a
 * response type — stay hand-written below and carry no such guarantee. */
type Schemas = components['schemas'];

/** `Omit` restricted to keys the source type actually has. The built-in accepts any string, so a
 * field the API renames would fall out of an omit list unnoticed and be re-added by the local
 * override beside it — reinstating the drift the generated types exist to catch. */
type StrictOmit<T, K extends keyof T> = Omit<T, K>;

export type Me = Schemas['MeResponseDto'];
export type UserRole = Me['role'];
export type AuthToken = Schemas['AuthTokenResponseDto'];

/** A single failed constraint, naming the field it failed on — the per-field breakdown of a
 * `ValidationErrorResponseDto`. */
export type FieldError = Schemas['FieldValidationErrorResponseDto'];

export class ApiError extends Error {
  status: number;

  /** Present only when the response body was a well-formed validation-error payload — a domain
   * exception's `{ status, message }` body carries no `errors` key, so this stays `undefined`
   * there. Form code branches on `isFieldValidationError` rather than checking this directly. */
  readonly fields?: FieldError[];

  /** Seconds until the caller may retry, read from the response's `Retry-After` header. Present
   * only when the header carries a non-negative number — absent for every response that omits it
   * or sends something this client cannot parse as one, in which case a caller falls back to its
   * own fixed cooldown window. */
  readonly retryAfterSeconds?: number;

  constructor(status: number, message: string, fields?: FieldError[], retryAfterSeconds?: number) {
    super(message);
    this.status = status;
    this.fields = fields;
    this.retryAfterSeconds = retryAfterSeconds;
  }
}

/** Narrows an unknown caught value to an `ApiError` carrying at least one field-level validation
 * error, the signal a form uses to render per-field messages instead of a single banner. Safe to
 * call on anything, including `null` and a plain `Error`. */
export function isFieldValidationError(err: unknown): err is ApiError & { fields: FieldError[] } {
  return err instanceof ApiError && Array.isArray(err.fields) && err.fields.length > 0;
}

// The single wording for an unreachable server, reached by every call site through
// `TransportError` rather than restated per page.
const TRANSPORT_ERROR_MESSAGE = 'Could not reach the server. Check your connection and try again.';

/** Thrown when `fetch` itself never produces an HTTP response — a dropped connection, DNS
 * failure, or the request's own timeout. `status` is `0`, the sentinel for "no server status to
 * report," distinguishing this from any status a server actually returned. */
export class TransportError extends ApiError {
  constructor() {
    super(0, TRANSPORT_ERROR_MESSAGE);
  }
}

// Bounds an ordinary JSON call: generous enough that a slow-but-working request still finishes,
// short enough that a genuinely dead connection surfaces as a transport error instead of hanging
// the UI forever. Model synthesis itself runs on the answer-question workflow and is polled or
// streamed separately — nothing awaits it inline through this helper.
const DEFAULT_TIMEOUT_MS = 30_000;

// A document upload carries a full file body over what may be a much slower link than the JSON
// calls above; the default budget would abort a large file partway through.
const UPLOAD_TIMEOUT_MS = 120_000;

function extractMessage(body: Record<string, unknown>, fallback: string): string {
  const { message } = body;
  if (typeof message === 'string') return message;
  // Defensive: the API now always sends a joined string, but a stale deployment may still send
  // class-validator's original array-of-messages shape.
  if (
    Array.isArray(message) &&
    message.every((entry): entry is string => typeof entry === 'string')
  ) {
    return message.join('; ');
  }
  return fallback;
}

function isFieldError(value: unknown): value is FieldError {
  return (
    value !== null &&
    typeof value === 'object' &&
    typeof (value as Record<string, unknown>).field === 'string' &&
    typeof (value as Record<string, unknown>).message === 'string'
  );
}

// Untrusted network input: an `errors` value that is not an array, or whose entries are not all
// well-formed, degrades to the valid subset (or `undefined` once that subset is empty) rather than
// throwing.
function extractFields(body: Record<string, unknown>): FieldError[] | undefined {
  const { errors } = body;
  if (!Array.isArray(errors)) return undefined;
  const valid = errors.filter(isFieldError);
  return valid.length > 0 ? valid : undefined;
}

// Untrusted network input: a missing header, a non-numeric value, or a negative one all degrade
// to `undefined` rather than producing a nonsensical cooldown.
function readRetryAfterSeconds(res: Response): number | undefined {
  const raw = res.headers.get('Retry-After');
  if (raw === null) return undefined;
  const seconds = Number(raw);
  return Number.isFinite(seconds) && seconds >= 0 ? seconds : undefined;
}

async function readErrorBody(res: Response): Promise<{ message: string; fields?: FieldError[] }> {
  const fallback = res.statusText || `HTTP ${res.status}`;
  try {
    const text = await res.text();
    if (!text) return { message: fallback };
    const body = JSON.parse(text) as unknown;
    if (body === null || typeof body !== 'object') return { message: fallback };
    const record = body as Record<string, unknown>;
    return { message: extractMessage(record, fallback), fields: extractFields(record) };
  } catch {
    return { message: fallback };
  }
}

/** Shared behind `request<T>()` and `requestBlob()`: the timeout/abort signal, the same-origin
 * credential, the 401-redirect rule, and turning a non-2xx response into `ApiError`. `parseBody`
 * runs inside the same try/finally as the fetch itself, so the timeout still covers a response
 * that sends headers and then stalls mid-body — whether that body is read as JSON text or as a
 * `Blob` — not just the initial `fetch` call, which settles as soon as headers arrive.
 */
async function fetchGuarded<T>(
  path: string,
  init: RequestInit | undefined,
  timeoutMs: number,
  parseBody: (res: Response) => Promise<T>,
): Promise<T> {
  const timeoutController = new AbortController();
  const timeoutId = setTimeout(() => timeoutController.abort(), timeoutMs);
  // No caller passes its own signal today; composing rather than overwriting keeps that case
  // correct if one ever does.
  const signal = init?.signal
    ? AbortSignal.any([init.signal, timeoutController.signal])
    : timeoutController.signal;

  try {
    // The credential is an HttpOnly cookie the SPA never handles itself; 'same-origin' is what
    // makes the browser attach it.
    const res = await fetch(`${API}${path}`, {
      ...init,
      credentials: 'same-origin',
      signal,
    });

    if (res.status === 401 && !path.startsWith('/auth/')) {
      window.location.assign('/login');
      throw new ApiError(401, 'Unauthorized');
    }

    if (!res.ok) {
      const { message, fields } = await readErrorBody(res);
      throw new ApiError(res.status, message, fields, readRetryAfterSeconds(res));
    }

    return await parseBody(res);
  } catch (err) {
    // Recognized as "no complete response arrived": this helper's own timeout, whether it fired
    // against the connection or against a stalled body, or the TypeError a browser throws for a
    // dropped connection, blocked CORS request, or DNS failure. `ApiError` passes through — a
    // server that answered is not a transport failure — and so does anything unrecognized, because
    // swallowing it into a generic message would hide a real defect rather than surface it.
    if (err instanceof ApiError) throw err;
    if (timeoutController.signal.aborted || err instanceof TypeError) {
      throw new TransportError();
    }
    throw err;
  } finally {
    clearTimeout(timeoutId);
  }
}

async function request<T>(path: string, init?: RequestInit): Promise<T> {
  const isFormData = init?.body instanceof FormData;
  const headers: Record<string, string> = {
    // A FormData body needs the browser to set its own multipart boundary; a fixed
    // 'application/json' header here would make the server unable to parse the upload.
    ...(isFormData ? {} : { 'Content-Type': 'application/json' }),
    ...(init?.headers as Record<string, string> | undefined),
  };

  return fetchGuarded(
    path,
    { ...init, headers },
    isFormData ? UPLOAD_TIMEOUT_MS : DEFAULT_TIMEOUT_MS,
    async (res) => {
      if (res.status === 204) {
        return undefined as T;
      }

      const text = await res.text();
      if (!text) return undefined as T;

      try {
        return JSON.parse(text) as T;
      } catch {
        // A 2xx whose body is not JSON means something answered in the API's place — a proxy landing
        // on the wrong upstream, or a captive portal. Raising `ApiError` holds the guarantee every
        // call site relies on, that this module throws `ApiError` and nothing else; the raw
        // `SyntaxError` would put "Unexpected token '<'" in front of the user instead.
        throw new ApiError(res.status, 'The server sent a response this app could not read.');
      }
    },
  );
}

/** Everything `request<T>()` shares (401-redirect, timeout, `ApiError`) with none of its JSON
 * assumptions — for the one response shape that is not JSON: a document version's stored bytes,
 * which the PDF pane needs as a `blob:` object URL rather than a direct-download href. */
async function requestBlob(path: string, init?: RequestInit): Promise<Blob> {
  return fetchGuarded(path, init, DEFAULT_TIMEOUT_MS, (res) => res.blob());
}

function jsonBody(data: unknown): RequestInit {
  return { body: JSON.stringify(data) };
}

export function register(email: string, password: string): Promise<Me> {
  return request<Me>('/auth/register', { method: 'POST', ...jsonBody({ email, password }) });
}

// The invitation dictates the account's email, tenant and role, so redemption collects only a
// password — the server ignores any email the caller might otherwise supply.
export function registerWithInvitation(password: string, invitationToken: string): Promise<Me> {
  return request<Me>('/auth/register', {
    method: 'POST',
    ...jsonBody({ password, invitationToken }),
  });
}

export async function login(email: string, password: string): Promise<AuthToken> {
  const result = await request<AuthToken>('/auth/login', {
    method: 'POST',
    ...jsonBody({ email, password }),
  });
  setSession(result.user);
  return result;
}

export async function logout(): Promise<void> {
  // Client-side logout must not depend on the server's answer: a CSRF rejection, a 500, or a
  // dropped connection must not leave the local session cache believing the user is still
  // authenticated just because the request that says otherwise never arrived.
  try {
    await request<void>('/auth/logout', { method: 'POST' });
  } finally {
    clearSession();
  }
}

export function getMe(): Promise<Me> {
  return request<Me>('/auth/me');
}

// ── Dashboard ────────────────────────────────────────────────────────────

export type DashboardSummary = Schemas['DashboardSummaryResponseDto'];

/** The tenant-wide counts `HomePage` renders as its summary cards. */
export function getDashboardSummary(): Promise<DashboardSummary> {
  return request<DashboardSummary>('/dashboard/summary');
}

// ── Documents ────────────────────────────────────────────────────────────

export type DocumentVersion = Schemas['DocumentVersionResponseDto'];
export type DocumentVersionIngestionStatus = DocumentVersion['ingestionStatus'];

// Named `EvidenceDocument`, not `Document` — the latter shadows the DOM global that the rest
// of the SPA (and jsdom in tests) relies on.
export type EvidenceDocument = Schemas['DocumentResponseDto'];
export type DocumentSourceKind = EvidenceDocument['sourceKind'];
export type DocumentWithVersions = Schemas['DocumentWithVersionsResponseDto'];

/** The envelope every paginated endpoint returns. Hand-written: the API declares these responses
 * with an example rather than a response type, so the OpenAPI document names no schema for the
 * envelope or for its element types. */
export interface WithCount<T> {
  docs: T[];
  count: number;
}

export function uploadDocument(
  file: File,
  options?: {
    documentId?: string;
    title?: string;
    // Ignored by the server when documentId is set — a new version never changes its document's
    // class. Never 'unclassified': that is what omitting this field already means.
    sourceClass?: DocumentSourceClass;
  },
): Promise<EvidenceDocument> {
  const formData = new FormData();
  formData.append('file', file);
  if (options?.documentId) formData.append('documentId', options.documentId);
  else formData.append('title', options?.title?.trim() || file.name);
  if (options?.sourceClass) formData.append('sourceClass', options.sourceClass);
  return request<EvidenceDocument>('/documents', { method: 'POST', body: formData });
}

export type SortDirection = 'asc' | 'desc';

/** The fields `/documents` will actually order by. Deliberately excludes `sizeBytes` and
 * `ingestionStatus`: both live on `DocumentVersion`, not `Document`, so the server cannot sort a
 * document list by them and offering the column would write a query it ignores. */
export type DocumentSortField = 'createdAt' | 'title' | 'sourceKind';

export function listDocuments(params?: {
  skip?: number;
  limit?: number;
  // Filters to documents whose CURRENT version has this ingestionStatus — 'failed' and
  // 'needs-ocr' are the corpus-health use cases. An older failed version superseded by a
  // completed one does not match.
  ingestionStatus?: DocumentVersionIngestionStatus;
  sort?: DocumentSortField;
  sortDir?: SortDirection;
}): Promise<WithCount<EvidenceDocument>> {
  const query = new URLSearchParams();
  if (params?.skip !== undefined) query.set('skip', String(params.skip));
  if (params?.limit !== undefined) query.set('limit', String(params.limit));
  if (params?.ingestionStatus !== undefined) query.set('ingestionStatus', params.ingestionStatus);
  if (params?.sort !== undefined) query.set('sort', params.sort);
  if (params?.sortDir !== undefined) query.set('sortDir', params.sortDir);
  const qs = query.toString();
  return request<WithCount<EvidenceDocument>>(`/documents${qs ? `?${qs}` : ''}`);
}

export function getDocumentById(id: string): Promise<DocumentWithVersions> {
  return request<DocumentWithVersions>(`/documents/${id}`);
}

// Admin-only, and irreversible: the server cascades to versions, chunks, facts and stored bytes.
// Answers that already cited this document keep their citations — see documents.service.ts.
export async function deleteDocument(id: string): Promise<void> {
  await request<void>(`/documents/${id}`, { method: 'DELETE' });
}

// A plain URL builder, not a `request<T>()` call: the browser fetches this href directly to
// drive a file download, so there is no JSON body for `request<T>()` to parse.
export function documentVersionContentUrl(versionId: string): string {
  return `${API}/documents/versions/${versionId}/content`;
}

/** The version's stored bytes as a `Blob`, not a followed download — the route sets
 * `Content-Disposition: attachment`, so an `<iframe src>` pointed at `documentVersionContentUrl()`
 * directly downloads the file instead of rendering it. This is the fetch behind the document
 * workbench's PDF pane, which turns the blob into an object URL itself. */
export function fetchDocumentVersionContent(versionId: string): Promise<Blob> {
  return requestBlob(`/documents/versions/${versionId}/content`);
}

// A plain URL builder, not a `request<T>()` call — a browser-native EventSource consumes this
// href directly, so there is no JSON body for `request<T>()` to parse. Takes the same `skip`/
// `limit` as `listDocuments` — the stream mirrors whichever page the caller is on, so the two
// must always agree on which documents to show.
export function documentEventsUrl(params?: { skip?: number; limit?: number }): string {
  const query = new URLSearchParams();
  if (params?.skip !== undefined) query.set('skip', String(params.skip));
  if (params?.limit !== undefined) query.set('limit', String(params.limit));
  const qs = query.toString();
  return `${API}/documents/events${qs ? `?${qs}` : ''}`;
}

// What a citation actually points at — the stored evidence_chunks, not a re-parse of the source
// document. Chunk granularity may span pages, ~12% overlap means adjacent chunks repeat some
// text, and elements quarantined at ingestion are absent entirely: not a faithful page render.
export type EvidenceChunkView = StrictOmit<Schemas['EvidenceChunkResponseDto'], 'locator'> & {
  // The document types a locator as a bare object: `Locator` is a discriminated union the API
  // describes in prose, and OpenAPI carries no schema for it.
  locator: Locator;
};

export function listVersionChunks(versionId: string): Promise<WithCount<EvidenceChunkView>> {
  return request<WithCount<EvidenceChunkView>>(`/documents/versions/${versionId}/chunks`);
}

/** Resolves a `Citation`'s `docVersionId` to the document it belongs to — the join a citation
 * cannot make on its own, since it carries no `documentId`. An id that does not resolve (unknown,
 * cross-tenant, or malformed) is silently absent from `docs`, never a 404 — a caller must index
 * the result by `versionId` rather than assume one row per requested id, or it will index out of
 * bounds. Hand-written rather than read from `Schemas`: the `{ docs, count }` envelope is never
 * named in the OpenAPI document, the same gap `WithCount<T>` itself documents above. */
export interface DocumentVersionLookup {
  versionId: string;
  documentId: string;
  documentTitle: string;
  versionNumber: number;
  sourceKind: DocumentSourceKind;
  withdrawn: boolean;
}

export function lookupDocumentVersions(
  versionIds: string[],
): Promise<WithCount<DocumentVersionLookup>> {
  const query = new URLSearchParams({ versionIds: versionIds.join(',') });
  return request<WithCount<DocumentVersionLookup>>(
    `/documents/versions/lookup?${query.toString()}`,
  );
}

// ── Questions & answers ─────────────────────────────────────────────────

export type AnswerRunStatus = Schemas['AnswerResponseDto']['runStatus'];

export type Locator =
  | {
      kind: 'pdf-page';
      extractorVersion: string;
      page: number;
      boundingBox?: { x: number; y: number; width: number; height: number };
    }
  | {
      kind: 'docx-paragraph';
      extractorVersion: string;
      paragraphIndex: number;
      headingPath: string[];
    }
  | { kind: 'xlsx-region'; extractorVersion: string; sheetName: string; range: string }
  | { kind: 'xlsx-cell'; extractorVersion: string; sheetName: string; cell: string }
  | { kind: 'text-block'; extractorVersion: string; blockIndex: number; headingPath: string[] }
  | { kind: 'pptx-slide'; extractorVersion: string; slide: number };

export interface Citation {
  docVersionId: string;
  sha256: string;
  chunkId: string;
  locator: Locator;
  quote: string;
}

export interface Claim {
  statement: string;
  citations: Citation[];
}

export interface ConflictingValue {
  value: number;
  unit: string;
  sourceChunkId: string;
}

export interface ConflictingFactKey {
  entity: string;
  metric: string;
  period: string;
}

export type InsufficientEvidenceReasonCode =
  | 'no_relevant_evidence'
  | 'evidence_does_not_address_question'
  | 'retrieved_evidence_contradicts_itself';

export type AnswerOutcome =
  | { kind: 'answered'; claims: Claim[] }
  // `reasonCode` is present only for a model-authored abstention (absent on legacy answers and on
  // the grounding gate's own degraded insufficient_evidence — see `answer.contract.ts`'s doc
  // comment on the API side). It never changes what is rendered here on its own: the API only ever
  // returns `kind: 'conflicting_evidence'` once it has independently verified the hint.
  | { kind: 'insufficient_evidence'; reason: string; reasonCode?: InsufficientEvidenceReasonCode }
  | { kind: 'conflicting_evidence'; factKey: ConflictingFactKey; values: ConflictingValue[] };

export type DroppedClaim = Schemas['DroppedClaimResponseDto'];
export type VerificationReport = Schemas['VerificationReportResponseDto'];

// `outcome` and `citations` are the two fields the document types as bare objects — both are
// discriminated unions the API describes in prose. Every other field, including whether it is
// optional, comes from the generated schema.
export type Answer = StrictOmit<Schemas['AnswerResponseDto'], 'outcome' | 'citations'> & {
  // Present only once runStatus is 'completed' — never render this as a final outcome before
  // then (see qa.controller.ts / answer.response.dto.ts).
  outcome?: AnswerOutcome;
  citations: Citation[];
};

export type StartQuestionResult = Schemas['StartQuestionResponseDto'];

export function startQuestion(questionText: string): Promise<StartQuestionResult> {
  return request<StartQuestionResult>('/questions', {
    method: 'POST',
    ...jsonBody({ questionText }),
  });
}

export function getAnswerById(id: string): Promise<Answer> {
  return request<Answer>(`/answers/${id}`);
}

/** The fields `/answers` will actually order by. Deliberately excludes every other
 * `AnswerResponseDto` field — offering a column the server ignores would write a query it never
 * honours. */
export type AnswerSortField = 'createdAt' | 'runStatus' | 'claimCoverage';

// Three independent optional filters, so this one builds its query with
// URLSearchParams rather than the ad-hoc template literals above.
export function listAnswers(params?: {
  skip?: number;
  limit?: number;
  runStatus?: AnswerRunStatus;
  sort?: AnswerSortField;
  sortDir?: SortDirection;
}): Promise<WithCount<Answer>> {
  const query = new URLSearchParams();
  if (params?.skip !== undefined) query.set('skip', String(params.skip));
  if (params?.limit !== undefined) query.set('limit', String(params.limit));
  if (params?.runStatus) query.set('runStatus', params.runStatus);
  if (params?.sort !== undefined) query.set('sort', params.sort);
  if (params?.sortDir !== undefined) query.set('sortDir', params.sortDir);
  const qs = query.toString();
  return request<WithCount<Answer>>(`/answers${qs ? `?${qs}` : ''}`);
}

// A plain URL builder, not a `request<T>()` call — a browser-native EventSource consumes this
// href directly, so there is no JSON body for `request<T>()` to parse.
export function answerEventsUrl(id: string): string {
  return `${API}/answers/${id}/events`;
}

// ── Retrieval ────────────────────────────────────────────────────────────

/** What `search_evidence` returns for one retrieved chunk, including the owning document's
 * `sourceClass` and `documentCreatedAt` for display alongside a result group. `score` is a fused
 * hybrid-retrieval relevance value — bounded above by a small constant, not a 0-1 similarity, per
 * the generated schema's own doc comment: rank this response's hits against each other with it,
 * never render it as a percentage, compare it across queries, or test it against a threshold. */
export type RetrievedChunkView = StrictOmit<Schemas['RetrievedChunkResponseDto'], 'locator'> & {
  // The document types a locator as a bare object: `Locator` is a discriminated union the API
  // describes in prose, and OpenAPI carries no schema for it.
  locator: Locator;
};

/**
 * `docs` plus `hasMore`, never a total. The store over-fetches non-deterministically, a
 * fail-closed score floor drops hits after fusion, and withdrawn versions are dropped after
 * that, so page boundaries can shift between two identical calls and a filter can leave a page
 * short while more results exist — a count taken at any single point would already be wrong by
 * the time it renders. `hasMore` is the only claim this endpoint can make honestly.
 */
export interface SearchEvidenceResult {
  docs: RetrievedChunkView[];
  hasMore: boolean;
}

/** The only field `/retrieval/search` sorts by — it exists only after fusion runs, unlike every
 * other list endpoint, which sorts a Mongo query directly. */
export type RetrievalSortField = 'score';

export function searchEvidence(params: {
  query: string;
  skip?: number;
  limit?: number;
  documentId?: string;
  sourceClass?: DocumentSourceClass;
  createdAfter?: string;
  createdBefore?: string;
  sort?: RetrievalSortField;
  sortDir?: SortDirection;
}): Promise<SearchEvidenceResult> {
  const query = new URLSearchParams({ query: params.query });
  if (params.skip !== undefined) query.set('skip', String(params.skip));
  if (params.limit !== undefined) query.set('limit', String(params.limit));
  if (params.documentId !== undefined) query.set('documentId', params.documentId);
  if (params.sourceClass !== undefined) query.set('sourceClass', params.sourceClass);
  if (params.createdAfter !== undefined) query.set('createdAfter', params.createdAfter);
  if (params.createdBefore !== undefined) query.set('createdBefore', params.createdBefore);
  if (params.sort !== undefined) query.set('sort', params.sort);
  if (params.sortDir !== undefined) query.set('sortDir', params.sortDir);
  return request<SearchEvidenceResult>(`/retrieval/search?${query.toString()}`);
}

// ── Conflicts ────────────────────────────────────────────────────────────

export type ConflictStatus = 'open' | 'resolved' | 'dismissed';

export interface ConflictValue {
  factId: string;
  value: number;
  unit: string;
  sourceChunkId: string;
  documentVersionId: string;
  locator: Locator;
  // True when documentVersionId currently carries withdrawnAt — the source file behind this side
  // of the disagreement is no longer at its source. The conflict itself stays open regardless.
  withdrawn: boolean;
}

export type ConflictRuleFired = 'authority' | 'recency' | 'none';

export interface Conflict {
  id: string;
  factKey: ConflictingFactKey;
  factIds: string[];
  values: ConflictValue[];
  magnitude: number;
  /**
   * The unit `magnitude` is expressed in. Required to render it at all: without it a cap-rate
   * spread and a dollar spread are indistinguishable, and magnitudes are not comparable across
   * rows carrying different units.
   */
  magnitudeUnit: string;
  status: ConflictStatus;
  createdAt: string;
  // True when one or more factIds no longer resolve to an ExtractedFact — the document that
  // produced them was deleted. proposedWinnerFactId, ruleFired and explanation are all absent
  // then: no survivorship policy runs over a fact set already known to be incomplete.
  unscorable: boolean;
  unscorableReason?: string;
  // True when the row's pack stamp no longer matches the deployed active pack — it was detected
  // under an ontology the deployment has since superseded, so what it says may not be what the
  // current ontology would compute. Always present, and unrelated to `unscorable`: a row can carry
  // either, both, or neither. A stale row is shown and labelled, never dropped from the list.
  stale: boolean;
  // Present only when `stale` is true: which pack detected the row against which is active now.
  staleReason?: string;
  proposedWinnerFactId?: string;
  ruleFired?: ConflictRuleFired;
  explanation?: string;
}

// Deliberately excludes `magnitude`: each row carries its own `magnitudeUnit`, so ordering by the
// bare number alone would rank a cap-rate spread against a dollar spread as if on the same scale.
export type ConflictSortField = 'createdAt' | 'status';

export function listConflicts(params?: {
  skip?: number;
  limit?: number;
  status?: ConflictStatus;
  sort?: ConflictSortField;
  sortDir?: SortDirection;
}): Promise<WithCount<Conflict>> {
  const query = new URLSearchParams();
  if (params?.skip !== undefined) query.set('skip', String(params.skip));
  if (params?.limit !== undefined) query.set('limit', String(params.limit));
  if (params?.status) query.set('status', params.status);
  if (params?.sort !== undefined) query.set('sort', params.sort);
  if (params?.sortDir !== undefined) query.set('sortDir', params.sortDir);
  const qs = query.toString();
  return request<WithCount<Conflict>>(`/conflicts${qs ? `?${qs}` : ''}`);
}

export function requestConflictResolution(
  conflictId: string,
  winningFactId: string,
): Promise<WorkflowRun> {
  return request<WorkflowRun>(`/conflicts/${conflictId}/resolution-requests`, {
    method: 'POST',
    ...jsonBody({ winningFactId }),
  });
}

// ── Approvals ────────────────────────────────────────────────────────────

export type ApprovalState = 'pending' | 'approved' | 'rejected' | 'timed_out';
export type ApprovalDecision = 'approved' | 'rejected';

export interface ApprovalSubject {
  entityType: string;
  entityId: string;
}

export interface Approval {
  id: string;
  subject: ApprovalSubject;
  action: string;
  summary: string;
  requestedBy?: string;
  // Underlying Temporal workflow id, present when this approval gates a workflow (matches
  // WorkflowRun.workflowId) — absent for an approval created outside one.
  workflowId?: string;
  state: ApprovalState;
  decidedBy?: string;
  decidedAt?: string;
  decisionReason?: string;
  createdAt: string;
}

export type ApprovalSortField = 'createdAt' | 'state' | 'decidedAt';

export function listApprovals(params?: {
  skip?: number;
  limit?: number;
  state?: ApprovalState;
  sort?: ApprovalSortField;
  sortDir?: SortDirection;
}): Promise<WithCount<Approval>> {
  const query = new URLSearchParams();
  if (params?.skip !== undefined) query.set('skip', String(params.skip));
  if (params?.limit !== undefined) query.set('limit', String(params.limit));
  if (params?.state) query.set('state', params.state);
  if (params?.sort !== undefined) query.set('sort', params.sort);
  if (params?.sortDir !== undefined) query.set('sortDir', params.sortDir);
  const qs = query.toString();
  return request<WithCount<Approval>>(`/approvals${qs ? `?${qs}` : ''}`);
}

export function decideApproval(
  id: string,
  decision: ApprovalDecision,
  reason?: string,
): Promise<Approval> {
  return request<Approval>(`/approvals/${id}/decision`, {
    method: 'POST',
    ...jsonBody(reason ? { decision, reason } : { decision }),
  });
}

// ── Workflow runs ────────────────────────────────────────────────────────

export type WorkflowRunStatus = 'queued' | 'running' | 'completed' | 'failed';

// Only the workflows that record a run row. `answer-question` and `ingest-document-version` run
// without one, so they never appear here. Absent on rows written before the field existed.
// `'rescan-conflicts'` is no longer a workflow this codebase starts; kept for existing rows that
// carry it, since no current code path writes it.
export type WorkflowRunType = 'resolve-conflict' | 'sync-source' | 'rescan-conflicts';

export interface WorkflowRun {
  id: string;
  workflowId: string;
  workflowType?: WorkflowRunType;
  status: WorkflowRunStatus;
  errorMessage?: string;
  /**
   * What the run acted on, written at creation. A resolve-conflict run records the conflict it is
   * resolving; a sync-source run records no subject and reads back empty. Both fields are written
   * together or not at all, so render a link only when both are present.
   */
  subjectId?: string;
  subjectType?: string;
  createdAt: string;
}

export function getWorkflowRunById(id: string): Promise<WorkflowRun> {
  return request<WorkflowRun>(`/workflow-runs/${id}`);
}

/**
 * `status` filters the stored row, not live engine state — the list endpoint never queries the
 * workflow engine, unlike the detail route and the event stream. A UI must not present this filter
 * as live.
 */
export type WorkflowRunSortField = 'createdAt' | 'status' | 'workflowType';

export function listWorkflowRuns(params?: {
  workflowId?: string;
  status?: WorkflowRunStatus;
  workflowType?: WorkflowRunType;
  skip?: number;
  limit?: number;
  sort?: WorkflowRunSortField;
  sortDir?: SortDirection;
}): Promise<WithCount<WorkflowRun>> {
  const query = new URLSearchParams();
  if (params?.workflowId) query.set('workflowId', params.workflowId);
  if (params?.status) query.set('status', params.status);
  if (params?.workflowType) query.set('workflowType', params.workflowType);
  if (params?.skip !== undefined) query.set('skip', String(params.skip));
  if (params?.limit !== undefined) query.set('limit', String(params.limit));
  if (params?.sort !== undefined) query.set('sort', params.sort);
  if (params?.sortDir !== undefined) query.set('sortDir', params.sortDir);
  const qs = query.toString();
  return request<WithCount<WorkflowRun>>(`/workflow-runs${qs ? `?${qs}` : ''}`);
}

// A plain URL builder, not a `request<T>()` call — a browser-native EventSource consumes this
// href directly, so there is no JSON body for `request<T>()` to parse.
export function workflowRunEventsUrl(id: string): string {
  return `${API}/workflow-runs/${id}/events`;
}

// ── Audit events ─────────────────────────────────────────────────────────

export interface AuditEventSubject {
  entityType: string;
  entityId: string;
}

export type AuditEventOrigin = 'api' | 'mcp';

export interface AuditEventView {
  id: string;
  actor: string;
  action: string;
  subject: AuditEventSubject;
  timestamp: string;
  correlationId: string;
  createdAt: string;
  origin: AuditEventOrigin;
  toolName?: string;
  refusalReason?: string;
  // Written only on 'sources.class_drift_applied' — the count of documents the remedy rewrote.
  // Absent on every other action.
  modifiedCount?: number;
}

export type AuditEventSortField = 'createdAt' | 'action' | 'origin';

// Five independent optional filters, so this one builds its query with
// URLSearchParams rather than the ad-hoc template literals above.
export function listAuditEvents(params?: {
  skip?: number;
  limit?: number;
  action?: string;
  entityType?: string;
  entityId?: string;
  origin?: AuditEventOrigin;
  refusalReason?: string;
  sort?: AuditEventSortField;
  sortDir?: SortDirection;
}): Promise<WithCount<AuditEventView>> {
  const query = new URLSearchParams();
  if (params?.skip !== undefined) query.set('skip', String(params.skip));
  if (params?.limit !== undefined) query.set('limit', String(params.limit));
  if (params?.action) query.set('action', params.action);
  if (params?.entityType) query.set('entityType', params.entityType);
  if (params?.entityId) query.set('entityId', params.entityId);
  if (params?.origin) query.set('origin', params.origin);
  if (params?.refusalReason) query.set('refusalReason', params.refusalReason);
  if (params?.sort !== undefined) query.set('sort', params.sort);
  if (params?.sortDir !== undefined) query.set('sortDir', params.sortDir);
  const qs = query.toString();
  return request<WithCount<AuditEventView>>(`/audit-events${qs ? `?${qs}` : ''}`);
}

// ── Sources ──────────────────────────────────────────────────────────────

export type SourceWithFileStates = Schemas['SourceWithFileStatesResponseDto'];

// The list and single-source endpoints return the same row without its per-file state; the
// document names only the detail shape, so the list shape derives from it.
export type Source = StrictOmit<SourceWithFileStates, 'fileStates'>;

export type SourceKind = Source['kind'];
export type SourceConnectivity = Source['connectivity'];
export type SourceReachability = Source['reachability'];

export type SourceFileState = Schemas['SourceFileStateResponseDto'];
export type SourceFileStateStatus = SourceFileState['status'];

export function createSource(input: {
  name: string;
  kind: SourceKind;
  path: string;
  // Required — its absence is the gap an estate's inventory pass exists to surface, so it is
  // never inferred or defaulted.
  owner: string;
  intervalMs?: number;
  enabled?: boolean;
  connectivity?: SourceConnectivity;
  reachability?: SourceReachability;
  tracked?: boolean;
  sourceClass?: DocumentSourceClass;
}): Promise<Source> {
  return request<Source>('/sources', { method: 'POST', ...jsonBody(input) });
}

// Deliberately excludes `fileCount`: it is computed in the response mapper from
// `fileStates.length`, never stored on the document, so there is no column to order by.
export type SourceSortField = 'name' | 'owner' | 'lastSyncAt' | 'createdAt';

/** Defaults to `name` ascending server-side, unlike most lists' newest-first — a source catalogue
 * is read by name, not by when it was added. */
export function listSources(pagination?: {
  skip?: number;
  limit?: number;
  // Partitions synced ('tracked: true') from inventory-only ('tracked: false') sources into two
  // separately-paged lists — cannot be done by filtering one fetched page client-side, since the
  // pager's count would be the combined total.
  tracked?: boolean;
  // Exact lastSyncStatus to filter by — currently only 'failed' is meaningful.
  lastSyncStatus?: string;
  sort?: SourceSortField;
  sortDir?: SortDirection;
  // Case-insensitive over name, path and owner, applied on both the tracked and inventory lists
  // before `count` is computed — the returned total describes exactly the rows a caller can page
  // through, not the tenant's full list.
  q?: string;
}): Promise<WithCount<Source>> {
  const query = new URLSearchParams();
  if (pagination?.skip !== undefined) query.set('skip', String(pagination.skip));
  if (pagination?.limit !== undefined) query.set('limit', String(pagination.limit));
  if (pagination?.tracked !== undefined) query.set('tracked', String(pagination.tracked));
  if (pagination?.lastSyncStatus !== undefined) {
    query.set('lastSyncStatus', pagination.lastSyncStatus);
  }
  if (pagination?.sort !== undefined) query.set('sort', pagination.sort);
  if (pagination?.sortDir !== undefined) query.set('sortDir', pagination.sortDir);
  if (pagination?.q) query.set('q', pagination.q);
  const qs = query.toString();
  return request<WithCount<Source>>(`/sources${qs ? `?${qs}` : ''}`);
}

export function getSourceById(id: string): Promise<SourceWithFileStates> {
  return request<SourceWithFileStates>(`/sources/${id}`);
}

// Every field independently optional and settable — the caller sends only what changed.
export function updateSource(
  id: string,
  input: {
    enabled?: boolean;
    connectivity?: SourceConnectivity;
    reachability?: SourceReachability;
    owner?: string;
    tracked?: boolean;
    sourceClass?: DocumentSourceClass;
  },
): Promise<Source> {
  return request<Source>(`/sources/${id}`, { method: 'PATCH', ...jsonBody(input) });
}

export function requestSourceSync(id: string): Promise<WorkflowRun> {
  return request<WorkflowRun>(`/sources/${id}/sync`, { method: 'POST' });
}

// Authority classification for the survivorship policy. 'unclassified' means nobody has declared
// one — never rendered as an option an uploader can pick, only as the default state.
export type DocumentSourceClass = EvidenceDocument['sourceClass'];

export interface SourceClassDrift {
  previousClass?: DocumentSourceClass;
  count: number;
}

export interface ApplySourceClassDrift {
  modifiedCount: number;
  previousClass?: DocumentSourceClass;
  sourceClass: DocumentSourceClass;
}

export function getSourceClassDrift(id: string): Promise<SourceClassDrift> {
  return request<SourceClassDrift>(`/sources/${id}/class-drift`);
}

export function applySourceClassDrift(id: string): Promise<ApplySourceClassDrift> {
  return request<ApplySourceClassDrift>(`/sources/${id}/class-drift/apply`, { method: 'POST' });
}

// ── API keys ─────────────────────────────────────────────────────────────

export interface ApiKey {
  id: string;
  name: string;
  tokenPrefix: string;
  expiresAt?: string;
  revokedAt?: string;
  // Stamped on every successful verify — the only signal distinguishing a live PAT from an
  // abandoned one. Absent means the key has never authenticated a request.
  lastUsedAt?: string;
  createdAt: string;
}

// The plaintext `token` lives only here — mint is the sole response shape that carries it.
// Nothing persists it beyond this call; a caller that loses this response has lost the token.
export interface MintedApiKey extends ApiKey {
  token: string;
}

export function mintApiKey(name: string, expiresAt?: string): Promise<MintedApiKey> {
  return request<MintedApiKey>('/api-keys', {
    method: 'POST',
    ...jsonBody(expiresAt ? { name, expiresAt } : { name }),
  });
}

export type ApiKeySortField = 'createdAt' | 'name' | 'lastUsedAt' | 'expiresAt';

export function listApiKeys(params?: {
  skip?: number;
  limit?: number;
  sort?: ApiKeySortField;
  sortDir?: SortDirection;
}): Promise<WithCount<ApiKey>> {
  const query = new URLSearchParams();
  if (params?.skip !== undefined) query.set('skip', String(params.skip));
  if (params?.limit !== undefined) query.set('limit', String(params.limit));
  if (params?.sort !== undefined) query.set('sort', params.sort);
  if (params?.sortDir !== undefined) query.set('sortDir', params.sortDir);
  const qs = query.toString();
  return request<WithCount<ApiKey>>(`/api-keys${qs ? `?${qs}` : ''}`);
}

export async function revokeApiKey(id: string): Promise<void> {
  await request<void>(`/api-keys/${id}`, { method: 'DELETE' });
}

// Rotates the key's token onto its existing row — same id, name and creation date, a fresh
// plaintext token shown exactly once. The previous token stops working the moment this call
// succeeds; only its hash was ever stored, so there is nothing to fall back to.
export function rotateApiKey(id: string): Promise<MintedApiKey> {
  return request<MintedApiKey>(`/api-keys/${id}/rotate`, { method: 'POST' });
}

// ── Invitations ──────────────────────────────────────────────────────────

export interface Invitation {
  id: string;
  email: string;
  role: UserRole;
  expiresAt: string;
  acceptedAt?: string;
  // Absent means the invitation is still live. A revoked invitation stays in the list rather than
  // being filtered out, so this is what tells the UI its token no longer works.
  revokedAt?: string;
  createdAt: string;
}

// The plaintext `token` lives only here, mirroring `MintedApiKey` — mint is the sole response
// shape that carries it, so nothing else in the SPA ever holds it.
export interface MintedInvitation extends Invitation {
  token: string;
}

export function mintInvitation(email: string, role: UserRole): Promise<MintedInvitation> {
  return request<MintedInvitation>('/invitations', {
    method: 'POST',
    ...jsonBody({ email, role }),
  });
}

export type InvitationSortField = 'createdAt' | 'email' | 'expiresAt' | 'role';

export function listInvitations(pagination?: {
  skip?: number;
  limit?: number;
  sort?: InvitationSortField;
  sortDir?: SortDirection;
}): Promise<WithCount<Invitation>> {
  const query = new URLSearchParams();
  if (pagination?.skip !== undefined) query.set('skip', String(pagination.skip));
  if (pagination?.limit !== undefined) query.set('limit', String(pagination.limit));
  if (pagination?.sort !== undefined) query.set('sort', pagination.sort);
  if (pagination?.sortDir !== undefined) query.set('sortDir', pagination.sortDir);
  const qs = query.toString();
  return request<WithCount<Invitation>>(`/invitations${qs ? `?${qs}` : ''}`);
}

// Kills an outstanding invitation inside its live window — both verify and accept refuse its
// token from this point on.
export async function revokeInvitation(id: string): Promise<void> {
  await request<void>(`/invitations/${id}`, { method: 'DELETE' });
}

// Rotates the invitation's token. Only a hash of the previous token was ever stored, so the old
// link stops working the moment this call succeeds — there is no way to recover or reactivate it.
export function resendInvitation(id: string): Promise<MintedInvitation> {
  return request<MintedInvitation>(`/invitations/${id}/resend`, { method: 'POST' });
}

// What InvitePage may learn about a token before it commits to a password: who is inviting and to
// what role, never whether the invited email already has an account.
export type InvitationPreview = Schemas['InvitationPreviewResponseDto'];

// Unauthenticated, called before InvitePage renders its form. The token goes in the POST body,
// matching InvitePage's own fragment-only handling of it — a query string would land it in a proxy
// or access log.
export function previewInvitation(token: string): Promise<InvitationPreview> {
  return request<InvitationPreview>('/invitations/preview', {
    method: 'POST',
    ...jsonBody({ token }),
  });
}

// ── Users ────────────────────────────────────────────────────────────────

export interface User {
  id: string;
  email: string;
  role: UserRole;
  createdAt: string;
}

export type UserSortField = 'createdAt' | 'email' | 'role';

/** Defaults to `email` ascending server-side, unlike the other lists' newest-first — a membership
 * roster is read by name, not by join date. */
export function listUsers(pagination?: {
  skip?: number;
  limit?: number;
  sort?: UserSortField;
  sortDir?: SortDirection;
}): Promise<WithCount<User>> {
  const query = new URLSearchParams();
  if (pagination?.skip !== undefined) query.set('skip', String(pagination.skip));
  if (pagination?.limit !== undefined) query.set('limit', String(pagination.limit));
  if (pagination?.sort !== undefined) query.set('sort', pagination.sort);
  if (pagination?.sortDir !== undefined) query.set('sortDir', pagination.sortDir);
  const qs = query.toString();
  return request<WithCount<User>>(`/users${qs ? `?${qs}` : ''}`);
}

export function changeUserRole(id: string, role: UserRole): Promise<User> {
  return request<User>(`/users/${id}/role`, { method: 'PATCH', ...jsonBody({ role }) });
}

export async function removeUser(id: string): Promise<void> {
  await request<void>(`/users/${id}`, { method: 'DELETE' });
}

/** Signs the member out of every browser session and disables every API key they hold — raising
 * their session epoch invalidates both, since `ApiKeysService.verify` checks a key's stored epoch
 * against the same `User.tokenVersion` a session cookie is checked against. */
export function revokeUserSessions(id: string): Promise<User> {
  return request<User>(`/users/${id}/revoke-sessions`, { method: 'POST' });
}

// ── Metrics ──────────────────────────────────────────────────────────────

/** One entry of the built-in metric ontology: the id facts and conflicts carry on the wire, the
 * label to show a reader instead of that id, and the unit the metric is normalised to. */
export interface Metric {
  id: string;
  label: string;
  canonicalUnit: string;
}

/** The full ontology, a fixed set rather than a paginated collection. Read-only: metrics are part
 * of the deployed code, so there is no route that adds or edits one. */
export function listMetrics(): Promise<Metric[]> {
  return request<Metric[]>('/metrics');
}

// ── Canonical entities ───────────────────────────────────────────────────

/** Whether a harvested alias resolves (`applied`), is recorded but inert (`proposed`), or has been
 * rejected by an operator (`revoked`). A `revoked` alias never returns to `applied`. */
export type HarvestedAliasStatus = 'proposed' | 'applied' | 'revoked';

/** An alias read out of a document's own parenthetical definition — `Northgate Business Park (the
 * "Property")` — with the quote and locator that make it checkable against the source bytes. */
export interface HarvestedAlias {
  alias: string;
  status: HarvestedAliasStatus;
  quote: string;
  locator: Locator;
  documentVersionId: string;
  harvestedAt: string;
}

// Hand-written rather than read from `Schemas` for the `list` shape: `GET /canonical-entities`
// declares its `@ApiResponse` with a description and examples but no `type`, so the OpenAPI
// document names no schema for the paginated form. The single-entity routes (`created`, `updated`,
// the harvested-alias actions) now do declare `type: CanonicalEntityResponseDto` — this interface
// still has to match those by hand, but drift there fails `web`'s typecheck against `schema.ts`
// rather than passing silently the way the whole shape did before.
export interface CanonicalEntity {
  id: string;
  canonicalName: string;
  aliases: string[];
  // Always present; empty until an alias is harvested from a document or proposed by a near-match
  // scan.
  harvestedAliases: HarvestedAlias[];
  createdAt: string;
}

export type CanonicalEntitySortField = 'canonicalNameNormalized' | 'createdAt';

/** Defaults to `canonicalNameNormalized` ascending server-side, unlike most lists' newest-first —
 * a canonical entity registry is read by name, not by when a row was created. */
export function listCanonicalEntities(params?: {
  skip?: number;
  limit?: number;
  sort?: CanonicalEntitySortField;
  sortDir?: SortDirection;
}): Promise<WithCount<CanonicalEntity>> {
  const query = new URLSearchParams();
  if (params?.skip !== undefined) query.set('skip', String(params.skip));
  if (params?.limit !== undefined) query.set('limit', String(params.limit));
  if (params?.sort !== undefined) query.set('sort', params.sort);
  if (params?.sortDir !== undefined) query.set('sortDir', params.sortDir);
  const qs = query.toString();
  return request<WithCount<CanonicalEntity>>(`/canonical-entities${qs ? `?${qs}` : ''}`);
}

export function createCanonicalEntity(input: {
  canonicalName: string;
  aliases?: string[];
}): Promise<CanonicalEntity> {
  return request<CanonicalEntity>('/canonical-entities', { method: 'POST', ...jsonBody(input) });
}

export function updateCanonicalEntity(
  id: string,
  input: { canonicalName?: string; aliases?: string[] },
): Promise<CanonicalEntity> {
  return request<CanonicalEntity>(`/canonical-entities/${id}`, {
    method: 'PATCH',
    ...jsonBody(input),
  });
}

export async function deleteCanonicalEntity(id: string): Promise<void> {
  await request<void>(`/canonical-entities/${id}`, { method: 'DELETE' });
}

/** Scans for unresolved fact entity names that are a suffix-only or punctuation-only near match of
 * a registered row — "Acme Tower, LLC" against a row named "Acme Tower" — and records each as a
 * `proposed` harvested alias on the row it was attributed to. Never applies one itself: a near
 * match is inference, not evidence, so confirming is always a separate, explicit call. */
export function scanNearMatches(): Promise<{ proposed: number }> {
  return request<{ proposed: number }>('/canonical-entities/near-matches/scan', {
    method: 'POST',
  });
}

/** Confirms a `proposed` harvested alias, folding it into resolution — the one-click confirmation
 * for both a document-read alias and a near-match proposal, since both land in the same `proposed`
 * state and this is the only path either can take to `applied`. */
export function applyHarvestedAlias(id: string, alias: string): Promise<CanonicalEntity> {
  return request<CanonicalEntity>(`/canonical-entities/${id}/harvested-aliases/apply`, {
    method: 'POST',
    ...jsonBody({ alias }),
  });
}

/** Rejects a harvested alias — document-read or near-match — so it never resolves. Terminal: a
 * later re-harvest or re-scan that would produce the same alias leaves the rejection standing. */
export function revokeHarvestedAlias(id: string, alias: string): Promise<CanonicalEntity> {
  return request<CanonicalEntity>(`/canonical-entities/${id}/harvested-aliases/revoke`, {
    method: 'POST',
    ...jsonBody({ alias }),
  });
}
