/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/auth/register': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['AuthController_register'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/login': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['AuthController_login'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/logout': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['AuthController_logout'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/me': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['AuthController_me'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/invitations': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['InvitationsController_list'];
    put?: never;
    post: operations['InvitationsController_mint'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/health': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['HealthController_getHealth'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/info': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['InfoController_getVersion'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/documents': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['DocumentsController_list'];
    put?: never;
    post: operations['DocumentsController_upload'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/documents/events': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['DocumentsController_streamEvents'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/documents/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['DocumentsController_getById'];
    put?: never;
    post?: never;
    delete: operations['DocumentsController_remove'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/documents/versions/{versionId}/content': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['DocumentsController_getVersionContent'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/documents/versions/{versionId}/chunks': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['DocumentsController_listVersionChunks'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/canonical-entities': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['CanonicalEntitiesController_list'];
    put?: never;
    post: operations['CanonicalEntitiesController_create'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/canonical-entities/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete: operations['CanonicalEntitiesController_remove'];
    options?: never;
    head?: never;
    patch: operations['CanonicalEntitiesController_update'];
    trace?: never;
  };
  '/conflicts': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['ConflictsController_list'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/conflicts/{id}/resolution-requests': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['ConflictsController_requestResolution'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/workflow-runs': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['WorkflowRunsController_list'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/workflow-runs/{id}/events': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['WorkflowRunsController_streamRun'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/workflow-runs/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['WorkflowRunsController_getById'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/approvals': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['ApprovalsController_list'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/approvals/{id}/decision': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['ApprovalsController_decide'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/questions': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['QaController_startQuestion'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/answers/{id}/events': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['QaController_streamAnswer'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/answers': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['QaController_listAnswers'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/answers/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['QaController_getAnswerById'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/retrieval/search': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['RetrievalController_search'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/sources': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['SourcesController_list'];
    put?: never;
    post: operations['SourcesController_create'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/sources/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['SourcesController_getById'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch: operations['SourcesController_update'];
    trace?: never;
  };
  '/sources/{id}/sync': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['SourcesController_requestSync'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/sources/{id}/class-drift': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['SourcesController_getClassDrift'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/sources/{id}/class-drift/apply': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['SourcesController_applyClassDrift'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/audit-events': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['AuditEventsController_list'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api-keys': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['ApiKeysController_list'];
    put?: never;
    post: operations['ApiKeysController_mint'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api-keys/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete: operations['ApiKeysController_revoke'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    RegisterRequestDto: {
      /**
       * @description Account email address. Required unless invitationToken is present — a token carries its own email, so this field is ignored when one is supplied.
       * @example user@example.com
       */
      email?: string;
      /**
       * @description Account password (8-72 characters).
       * @example correct-horse-battery-staple
       */
      password: string;
      /**
       * @description Single-use invitation token. When present, the invitation determines the tenant, role and email the account joins with.
       * @example eo_inv_9f8c12ab34cd56ef
       */
      invitationToken?: string;
    };
    MeResponseDto: {
      /**
       * @description Account identifier.
       * @example 65f1c2e4a1b2c3d4e5f6a7b8
       */
      id: string;
      /**
       * @description Account email address.
       * @example user@example.com
       */
      email: string;
      /**
       * @description Account role.
       * @example member
       * @enum {string}
       */
      role: 'admin' | 'member';
      /**
       * Format: date-time
       * @description Account creation timestamp.
       * @example 2026-07-01T00:00:00.000Z
       */
      createdAt: string;
    };
    LoginRequestDto: {
      /**
       * @description Account email address.
       * @example user@example.com
       */
      email: string;
      /**
       * @description Account password (8-72 characters).
       * @example correct-horse-battery-staple
       */
      password: string;
    };
    AuthTokenResponseDto: {
      user: components['schemas']['MeResponseDto'];
    };
    CreateInvitationRequestDto: {
      /**
       * @description Email address to invite.
       * @example colleague@example.com
       */
      email: string;
      /**
       * @description Role the invitee joins the tenant with.
       * @example member
       * @enum {string}
       */
      role: 'admin' | 'member';
    };
    HealthResponseDto: {
      /**
       * @description Overall health status.
       * @example ok
       * @enum {string}
       */
      status: 'ok' | 'degraded';
      /**
       * @description Mongo connectivity, checked via an admin ping (~2s timeout).
       * @example up
       * @enum {string}
       */
      mongo: 'up' | 'down';
    };
    InfoResponseDto: {
      /**
       * @description Application package version.
       * @example 1.0.0
       */
      version: string;
    };
    DocumentVersionResponseDto: {
      /**
       * @description Version identifier.
       * @example 65f1c2e4a1b2c3d4e5f6a7b9
       */
      id: string;
      /**
       * @description Sequential version number, starting at 1.
       * @example 1
       */
      versionNumber: number;
      /**
       * @description sha256 of the version bytes — what a citation pins.
       * @example e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b85
       */
      sha256: string;
      /**
       * @description Size of the version bytes, in bytes.
       * @example 245760
       */
      sizeBytes: number;
      /**
       * @description Progress marker for the ingestion workflow started on upload.
       * @example pending
       * @enum {string}
       */
      ingestionStatus: 'pending' | 'completed' | 'facts-failed' | 'failed' | 'needs-ocr';
      /**
       * @description Present when ingestionStatus is "failed" or "needs-ocr" — the parser exception message from the attempt that set that status.
       * @example Document has 3 page(s) but no extractable text on any of them (likely a scanned image with no embedded text layer); OCR is out of scope for this parser
       */
      ingestionFailureReason?: string;
      /**
       * @description Non-empty when this version was ingested with known fidelity loss; each entry states one reason. Empty for a version with no fidelity loss.
       * @example [
       *       "Document has 3 page(s) but no extractable text on any of them; falling back to OCR-only extraction for those pages"
       *     ]
       */
      reducedFidelityReasons: string[];
      /**
       * Format: date-time
       * @description Version creation timestamp.
       * @example 2026-07-01T00:00:00.000Z
       */
      createdAt: string;
    };
    DocumentResponseDto: {
      /**
       * @description Document identifier.
       * @example 65f1c2e4a1b2c3d4e5f6a7b8
       */
      id: string;
      /**
       * @description Document title.
       * @example Q3 Rent Roll
       */
      title: string;
      /**
       * @description Extractor pipeline kind.
       * @example xlsx
       * @enum {string}
       */
      sourceKind: 'pdf' | 'docx' | 'xlsx' | 'pptx' | 'csv' | 'tsv' | 'txt' | 'md';
      /**
       * @description Raw content type as uploaded.
       * @example application/vnd.openxmlformats-officedocument.spreadsheetml.sheet
       */
      mimeType: string;
      /**
       * @description Authority classification for this document. 'unclassified' means nobody has declared one — the survivorship policy treats that as no authority information, not the lowest rank.
       * @example unclassified
       * @enum {string}
       */
      sourceClass: 'crm-export' | 'pm-export' | 'spreadsheet' | 'memo' | 'report' | 'unclassified';
      currentVersion: components['schemas']['DocumentVersionResponseDto'];
      /**
       * Format: date-time
       * @description Document creation timestamp.
       * @example 2026-07-01T00:00:00.000Z
       */
      createdAt: string;
    };
    DocumentWithVersionsResponseDto: {
      /**
       * @description Document identifier.
       * @example 65f1c2e4a1b2c3d4e5f6a7b8
       */
      id: string;
      /**
       * @description Document title.
       * @example Q3 Rent Roll
       */
      title: string;
      /**
       * @description Extractor pipeline kind.
       * @example xlsx
       * @enum {string}
       */
      sourceKind: 'pdf' | 'docx' | 'xlsx' | 'pptx' | 'csv' | 'tsv' | 'txt' | 'md';
      /**
       * @description Raw content type as uploaded.
       * @example application/vnd.openxmlformats-officedocument.spreadsheetml.sheet
       */
      mimeType: string;
      /**
       * @description Authority classification for this document. 'unclassified' means nobody has declared one — the survivorship policy treats that as no authority information, not the lowest rank.
       * @example unclassified
       * @enum {string}
       */
      sourceClass: 'crm-export' | 'pm-export' | 'spreadsheet' | 'memo' | 'report' | 'unclassified';
      currentVersion: components['schemas']['DocumentVersionResponseDto'];
      /**
       * Format: date-time
       * @description Document creation timestamp.
       * @example 2026-07-01T00:00:00.000Z
       */
      createdAt: string;
      /** @description Full version history, oldest first. */
      versions: components['schemas']['DocumentVersionResponseDto'][];
    };
    EvidenceChunkResponseDto: {
      /**
       * @description Content-addressed chunk identifier.
       * @example a1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6
       */
      id: string;
      /**
       * @description Chunk text, exactly as stored at ingestion.
       * @example The cap rate for Northgate Business Park is approximately 6.10%.
       */
      text: string;
      /**
       * @description Token count of this chunk, as measured at ingestion.
       * @example 128
       */
      tokenCount: number;
      /**
       * @description Where this chunk's text came from in the source document.
       * @example {
       *       "kind": "pdf-page",
       *       "extractorVersion": "v1",
       *       "page": 3
       *     }
       */
      locator: Record<string, never>;
    };
    CreateCanonicalEntityRequestDto: {
      /**
       * @description Canonical display name this row registers alternate spellings against.
       * @example Northgate Business Park
       */
      canonicalName: string;
      /**
       * @description Alternate spellings that should resolve to canonicalName.
       * @example [
       *       "Northgate Bus. Park"
       *     ]
       */
      aliases?: string[];
    };
    UpdateCanonicalEntityRequestDto: {
      /**
       * @description New canonical display name for this row.
       * @example Northgate Business Park
       */
      canonicalName?: string;
      /**
       * @description Replaces the full alias list. Omit to leave the current aliases untouched.
       * @example [
       *       "Northgate Bus. Park"
       *     ]
       */
      aliases?: string[];
    };
    RequestConflictResolutionRequestDto: {
      /**
       * @description ExtractedFact id proposed as this conflict's correct value — the workflow gates this proposal behind a human, it does not choose it.
       * @example 65f1c2e4a1b2c3d4e5f6a7b9
       */
      winningFactId: string;
    };
    DecideApprovalRequestDto: {
      /**
       * @description Human decision on the pending approval request.
       * @example approved
       * @enum {string}
       */
      decision: 'approved' | 'rejected';
      /**
       * @description Optional rationale for the decision.
       * @example Evidence checks out; the spreadsheet figure is the current underwriting value.
       */
      reason?: string;
    };
    StartQuestionRequestDto: {
      /**
       * @description Natural-language question to answer from the evidence corpus.
       * @example What is the cap rate for Northgate Business Park in Q1 2025?
       */
      questionText: string;
    };
    StartQuestionResponseDto: {
      /**
       * @description Answer identifier. Poll GET /answers/{id} for the run's status and outcome.
       * @example 65f1c2e4a1b2c3d4e5f6a7b8
       */
      id: string;
      /**
       * @description Initial workflow run status — always queued at creation.
       * @example queued
       * @enum {string}
       */
      runStatus: 'queued' | 'running' | 'completed' | 'failed';
    };
    DroppedClaimResponseDto: {
      /**
       * @description The model-authored claim statement that was dropped during verification.
       * @example The cap rate is approximately 6.10%.
       */
      statement: string;
      /**
       * @description Why the claim was dropped.
       * @example quote did not match the source chunk
       */
      reason: string;
    };
    VerificationReportResponseDto: {
      /**
       * @description Number of model-authored claims that survived server-side citation verification.
       * @example 3
       */
      verifiedClaimCount: number;
      /**
       * @description Total number of model-authored claims before verification.
       * @example 4
       */
      totalClaimCount: number;
      /** @description Claims dropped during verification, with the reason each was dropped. */
      droppedClaims: components['schemas']['DroppedClaimResponseDto'][];
    };
    AnswerUsageResponseDto: {
      /**
       * @description Prompt tokens for the synthesis call.
       * @example 1240
       */
      promptTokens: number;
      /**
       * @description Completion tokens for the synthesis call.
       * @example 180
       */
      completionTokens: number;
      /**
       * @description Synthesis call cost in USD.
       * @example 0.0042
       */
      costUsd: number;
    };
    AnswerResponseDto: {
      /**
       * @description Answer identifier.
       * @example 65f1c2e4a1b2c3d4e5f6a7b8
       */
      id: string;
      /**
       * @description The question this answer was requested for.
       * @example What is the cap rate for Northgate Business Park in Q1 2025?
       */
      questionText: string;
      /**
       * @description Workflow lifecycle status — separate from the answer outcome below.
       * @example completed
       * @enum {string}
       */
      runStatus: 'queued' | 'running' | 'completed' | 'failed';
      /**
       * @description The gate-verified outcome, present only once runStatus is 'completed'. For kind: 'answered', claims are the survivors of server-side grounding verification, never the model's raw, unverified claim set. One of kind: 'answered' | 'insufficient_evidence' | 'conflicting_evidence'.
       * @example {
       *       "kind": "answered",
       *       "claims": [
       *         {
       *           "statement": "The cap rate is approximately 6.10%.",
       *           "citations": []
       *         }
       *       ]
       *     }
       */
      outcome?: Record<string, never>;
      /**
       * @description Fraction of the model-authored claims that survived server-side verification.
       * @example 0.75
       */
      claimCoverage?: number;
      /**
       * @description Number of evidence chunks retrieved for this run, present only once runStatus is 'completed'.
       * @example 12
       */
      retrievedChunkCount?: number;
      /** @description Server-computed claim verification summary, present only once runStatus is 'completed'. */
      verificationReport?: components['schemas']['VerificationReportResponseDto'];
      /** @description Citations backing the server-verified claims, flattened across all claims. */
      citations: Record<string, never>[];
      /** @description Conflict identifiers relevant to this answer, if any were detected. */
      conflictIds: string[];
      /**
       * Format: date-time
       * @description Answer creation timestamp.
       * @example 2026-07-01T00:00:00.000Z
       */
      createdAt: string;
      /** @description Cited document versions that currently carry withdrawnAt, resolved fresh on every read — never persisted alongside citations, so this can change between two reads of the same answer without the answer itself changing. */
      withdrawnCitedDocVersionIds: string[];
      /** @description Token and cost accounting for the QA synthesis call, present only once runStatus is 'completed'. */
      usage?: components['schemas']['AnswerUsageResponseDto'];
    };
    CreateSourceRequestDto: {
      /**
       * @description Human-readable name for this source.
       * @example Deal Room Inbox
       */
      name: string;
      /**
       * @description Which connector syncs this source.
       * @example local-folder
       * @enum {string}
       */
      kind: 'local-folder';
      /**
       * @description The connector's location for this source — a folder path for 'local-folder'.
       * @example deal-room
       */
      path: string;
      /**
       * @description Per-source override of the global sync interval, in milliseconds. Omit to use the configured default.
       * @example 60000
       */
      intervalMs?: number;
      /**
       * @description Whether the sync loop is allowed to run for this source. Defaults to true.
       * @default true
       * @example true
       */
      enabled: boolean;
      /**
       * @description How this source's bytes get into the corpus. Defaults to 'connector'.
       * @default connector
       * @example connector
       * @enum {string}
       */
      connectivity: 'connector' | 'export-only' | 'manual';
      /**
       * @description Whether the estate's own access posture lets this system reach this source at all. Defaults to 'live'.
       * @default live
       * @example live
       * @enum {string}
       */
      reachability: 'live' | 'possible' | 'prohibited';
      /**
       * @description Person or team accountable for this source. Required — its absence is the gap an estate's inventory pass exists to surface, so it is never inferred or defaulted.
       * @example Jane Doe, IT
       */
      owner: string;
      /**
       * @description Whether the sync loop may ever run for this source. 'false' marks an inventory-only row catalogued for the estate map but never synced. Defaults to true.
       * @default true
       * @example true
       */
      tracked: boolean;
      /**
       * @description Default document classification a document created from this source's sync pass inherits. Defaults to 'unclassified'.
       * @default unclassified
       * @example unclassified
       * @enum {string}
       */
      sourceClass: 'crm-export' | 'pm-export' | 'spreadsheet' | 'memo' | 'report' | 'unclassified';
    };
    SourceFileStateResponseDto: {
      /**
       * @description The file's path relative to the source's root.
       * @example contracts/lease-agreement.pdf
       */
      path: string;
      /**
       * @description 'failed' when the most recent sync attempt for this file recorded an error.
       * @example failed
       * @enum {string}
       */
      status: 'ok' | 'failed';
      /**
       * @description Error detail from the most recent failed sync attempt for this file.
       * @example Could not resolve a document type for 'contracts/lease-agreement.pdf'
       */
      lastError?: string;
      /**
       * @description The file's on-disk modification time, epoch milliseconds.
       * @example 1753920000000
       */
      mtimeMs: number;
    };
    SourceWithFileStatesResponseDto: {
      /**
       * @description Source identifier.
       * @example 65f1c2e4a1b2c3d4e5f6a7b8
       */
      id: string;
      /**
       * @description Human-readable name for this source.
       * @example Deal Room Inbox
       */
      name: string;
      /**
       * @description Which connector syncs this source.
       * @example local-folder
       * @enum {string}
       */
      kind: 'local-folder';
      /**
       * @description The connector's location for this source — a folder path for 'local-folder'.
       * @example deal-room
       */
      path: string;
      /**
       * @description Whether the sync loop is allowed to run for this source.
       * @example true
       */
      enabled: boolean;
      /**
       * @description Per-source override of the global sync interval, in milliseconds. Absent means the configured default applies.
       * @example 60000
       */
      intervalMs?: number;
      /**
       * Format: date-time
       * @description When the most recent sync attempt finished.
       * @example 2026-07-01T00:00:00.000Z
       */
      lastSyncAt?: string;
      /**
       * @description Outcome of the most recent sync attempt — 'ok' or 'failed'.
       * @example ok
       */
      lastSyncStatus?: string;
      /**
       * @description Error detail, present only when lastSyncStatus is failed.
       * @example ENOENT: no such file or directory
       */
      lastSyncError?: string;
      /**
       * @description Number of files this source has synced state for.
       * @example 42
       */
      fileCount: number;
      /**
       * @description How this source's bytes get into the corpus.
       * @example connector
       * @enum {string}
       */
      connectivity: 'connector' | 'export-only' | 'manual';
      /**
       * @description Whether the estate's own access posture lets this system reach this source at all.
       * @example live
       * @enum {string}
       */
      reachability: 'live' | 'possible' | 'prohibited';
      /**
       * @description Person or team accountable for this source. Absent means nobody has said yet.
       * @example Jane Doe, IT
       */
      owner?: string;
      /**
       * @description Whether the sync loop may ever run for this source. 'false' marks an inventory-only row.
       * @example true
       */
      tracked: boolean;
      /**
       * @description Default document classification a document created from this source's sync pass inherits.
       * @example unclassified
       * @enum {string}
       */
      sourceClass: 'crm-export' | 'pm-export' | 'spreadsheet' | 'memo' | 'report' | 'unclassified';
      /**
       * Format: date-time
       * @description Source creation timestamp.
       * @example 2026-07-01T00:00:00.000Z
       */
      createdAt: string;
      /** @description Per-file sync state, one entry per file this source has ever seen. */
      fileStates: components['schemas']['SourceFileStateResponseDto'][];
    };
    UpdateSourceRequestDto: {
      /**
       * @description Whether the sync loop is allowed to run for this source.
       * @example false
       */
      enabled?: boolean;
      /**
       * @description How this source's bytes get into the corpus.
       * @example export-only
       * @enum {string}
       */
      connectivity?: 'connector' | 'export-only' | 'manual';
      /**
       * @description Whether the estate's own access posture lets this system reach this source at all.
       * @example possible
       * @enum {string}
       */
      reachability?: 'live' | 'possible' | 'prohibited';
      /**
       * @description Person or team accountable for this source.
       * @example Jane Doe, IT
       */
      owner?: string;
      /**
       * @description Whether the sync loop may ever run for this source. 'false' marks an inventory-only row catalogued for the estate map but never synced.
       * @example false
       */
      tracked?: boolean;
      /**
       * @description Default document classification a document created from this source's sync pass inherits. Correcting this does not rewrite documents already ingested under the old class.
       * @example crm-export
       * @enum {string}
       */
      sourceClass?: 'crm-export' | 'pm-export' | 'spreadsheet' | 'memo' | 'report' | 'unclassified';
    };
    CreateApiKeyRequestDto: {
      /**
       * @description Human-readable name for this key.
       * @example CI integration
       */
      name: string;
      /**
       * Format: date-time
       * @description When this key stops working, at most one year out. Omit to use the default TTL (`apiKeys.defaultTtlDays` from config).
       * @example 2026-12-31T00:00:00.000Z
       */
      expiresAt?: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  AuthController_register: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['RegisterRequestDto'];
      };
    };
    responses: {
      /** @description Account created. */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['MeResponseDto'];
        };
      };
      /**
       * @description The invitation's email already has an account. The existing account is untouched.
       *
       *     The invitation token is unknown, expired, or already used.
       */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      /** @description Email is already registered. */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
    };
  };
  AuthController_login: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['LoginRequestDto'];
      };
    };
    responses: {
      /** @description Authenticated successfully. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AuthTokenResponseDto'];
        };
      };
      /** @description Invalid email or password. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
    };
  };
  AuthController_logout: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Session cookie cleared. The underlying JWT is not revoked and stays valid until it expires. */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description No or invalid token provided. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
    };
  };
  AuthController_me: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Current authenticated account. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['MeResponseDto'];
        };
      };
      /** @description No or invalid token provided. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
    };
  };
  InvitationsController_list: {
    parameters: {
      query?: {
        /** @description Comma-separated fields to include; `_id` is always returned. */
        select?: string;
        /** @description Number of documents to skip (offset). */
        skip?: number;
        /** @description Maximum number of documents to return. */
        limit?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The tenant's invitations. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      /** @description Only an admin may mint or list invitations. */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
    };
  };
  InvitationsController_mint: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateInvitationRequestDto'];
      };
    };
    responses: {
      /** @description The newly minted invitation, including its plaintext token — shown exactly once. */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      /** @description Only an admin may mint or list invitations. */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      /** @description The invited email already has an account. */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
    };
  };
  HealthController_getHealth: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Health check status returned. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HealthResponseDto'];
        };
      };
    };
  };
  InfoController_getVersion: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description App version returned. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['InfoResponseDto'];
        };
      };
    };
  };
  DocumentsController_list: {
    parameters: {
      query?: {
        /** @description Comma-separated fields to include; `_id` is always returned. */
        select?: string;
        /** @description Number of documents to skip (offset). */
        skip?: number;
        /** @description Maximum number of documents to return. */
        limit?: number;
        /** @description Filter to documents whose CURRENT version has this ingestionStatus — 'failed' and 'needs-ocr' are the corpus-health use cases. An older failed version superseded by a newer completed one does not match, the same semantics `HomePage.tsx`'s client-side filter already uses. Omit to list every document regardless of ingestion outcome. */
        ingestionStatus?: 'pending' | 'completed' | 'facts-failed' | 'failed' | 'needs-ocr';
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Paginated list of documents with their current version. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
    };
  };
  DocumentsController_upload: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'multipart/form-data': {
          /** Format: binary */
          file?: string;
          documentId?: string;
          title?: string;
          requireApproval?: boolean;
          sourceClass?: string;
        };
      };
    };
    responses: {
      /** @description Document uploaded. Unchanged bytes for an existing document return the existing version. */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['DocumentResponseDto'];
        };
      };
      /** @description Document does not exist. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      /** @description Content type is not one of pdf, docx, xlsx. */
      415: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
    };
  };
  DocumentsController_streamEvents: {
    parameters: {
      query?: {
        /** @description Comma-separated fields to include; `_id` is always returned. */
        select?: string;
        /** @description Number of documents to skip (offset). */
        skip?: number;
        /** @description Maximum number of documents to return. */
        limit?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description text/event-stream. Polls every 3s. `documents` events carry the exact shape GET /documents returns; a `heartbeat` event fires every 15s; a terminal `error` event means the client should fall back to polling GET /documents. Re-checks the connecting session every 30s and closes if it is gone or moved tenants, and closes unconditionally once the connection has been open for the configured max stream lifetime — this stream's own list has no terminal state of its own, unlike the answer/run streams. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description The caller's tenant or user is already at its open-SSE-stream cap. */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
    };
  };
  DocumentsController_getById: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Document with its full version history. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['DocumentWithVersionsResponseDto'];
        };
      };
      /** @description Document does not exist. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
    };
  };
  DocumentsController_remove: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Document deleted along with its versions, stored bytes, evidence chunks, and extracted facts. Conflicts referencing a deleted fact are resolved as superseded, not deleted. */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Caller does not hold the admin role required to delete a document. */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      /** @description Document does not exist. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
    };
  };
  DocumentsController_getVersionContent: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        versionId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Raw bytes of the stored document version, served as a file download with a sanitized filename. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Document version does not exist, belongs to another tenant, or its stored bytes carry a different tenant stamp — all three are indistinguishable from each other. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
    };
  };
  DocumentsController_listVersionChunks: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        versionId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The version's evidence chunks, in locator order. Not a re-parse of the source document — chunk granularity may span pages, ~12% overlap means adjacent chunks repeat some text, and elements quarantined at ingestion are absent entirely. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['EvidenceChunkResponseDto'];
        };
      };
      /** @description Document version does not exist or belongs to another tenant. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
    };
  };
  CanonicalEntitiesController_list: {
    parameters: {
      query?: {
        /** @description Comma-separated fields to include; `_id` is always returned. */
        select?: string;
        /** @description Number of documents to skip (offset). */
        skip?: number;
        /** @description Maximum number of documents to return. */
        limit?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The tenant's registered canonical entities. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
    };
  };
  CanonicalEntitiesController_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateCanonicalEntityRequestDto'];
      };
    };
    responses: {
      /** @description The canonical entity row that was created. */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      /** @description Caller does not hold the admin role required to author this registry. */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      /** @description A canonical entity with this name already exists for this tenant. */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
    };
  };
  CanonicalEntitiesController_remove: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The canonical entity row was deleted. */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Caller does not hold the admin role required to author this registry. */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      /** @description No canonical entity with this id exists for the caller's tenant. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
    };
  };
  CanonicalEntitiesController_update: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateCanonicalEntityRequestDto'];
      };
    };
    responses: {
      /** @description The canonical entity row after this update. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      /** @description Caller does not hold the admin role required to author this registry. */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      /** @description No canonical entity with this id exists for the caller's tenant. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      /** @description A canonical entity with this name already exists for this tenant. */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
    };
  };
  ConflictsController_list: {
    parameters: {
      query?: {
        /** @description Comma-separated fields to include; `_id` is always returned. */
        select?: string;
        /** @description Number of documents to skip (offset). */
        skip?: number;
        /** @description Maximum number of documents to return. */
        limit?: number;
        /** @description Exact conflict status to filter by. */
        status?: 'open' | 'resolved' | 'dismissed';
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Paginated list of detected conflicts. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
    };
  };
  ConflictsController_requestResolution: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['RequestConflictResolutionRequestDto'];
      };
    };
    responses: {
      /** @description A resolveConflict workflow was started to gate the proposed winner behind a human. */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      /** @description Conflict does not exist. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      /** @description Conflict is not open, or winningFactId is not one of its own facts. */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
    };
  };
  WorkflowRunsController_list: {
    parameters: {
      query?: {
        /** @description Comma-separated fields to include; `_id` is always returned. */
        select?: string;
        /** @description Number of documents to skip (offset). */
        skip?: number;
        /** @description Maximum number of documents to return. */
        limit?: number;
        /** @description Underlying Temporal workflow id to filter by. Omit it to list every run for the caller's tenant, most recent first. */
        workflowId?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Runs for the caller's tenant, most recent first. Filters to a single workflow when workflowId is given; omitting it lists every run. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
    };
  };
  WorkflowRunsController_streamRun: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description text/event-stream. Polls every 1.5s until status reaches a terminal state, emitting the final state before closing. `run` events carry the exact shape GET /workflow-runs/:id returns; `approvals` events carry the exact shape GET /approvals returns (the tenant's whole pending inbox, not just this run's); a `heartbeat` event fires every 15s; a terminal `error` event means the client should fall back to polling both endpoints. Re-checks the connecting session every 30s and closes if it is gone or moved tenants. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description The caller's tenant or user is already at its open-SSE-stream cap. */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
    };
  };
  WorkflowRunsController_getById: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The run's current status, best-effort refreshed from the live workflow engine. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      /** @description WorkflowRun does not exist. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
    };
  };
  ApprovalsController_list: {
    parameters: {
      query?: {
        /** @description Comma-separated fields to include; `_id` is always returned. */
        select?: string;
        /** @description Number of documents to skip (offset). */
        skip?: number;
        /** @description Maximum number of documents to return. */
        limit?: number;
        /** @description Approval state to filter by. Defaults to `pending` — this endpoint is the pending inbox. */
        state?: 'pending' | 'approved' | 'rejected' | 'timed_out';
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Paginated pending-approval inbox. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
    };
  };
  ApprovalsController_decide: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['DecideApprovalRequestDto'];
      };
    };
    responses: {
      /** @description The approval after recording the decision. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      /** @description Caller does not hold the admin role required to decide an approval. */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      /** @description Approval does not exist for this tenant. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      /** @description Approval was already decided. */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
    };
  };
  QaController_startQuestion: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['StartQuestionRequestDto'];
      };
    };
    responses: {
      /** @description Question accepted; a workflow was started to produce the answer. */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['StartQuestionResponseDto'];
        };
      };
      /** @description questionText is missing, empty, or not a string. */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
    };
  };
  QaController_streamAnswer: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description text/event-stream. Polls every 1.5s until runStatus reaches a terminal state, emitting the final state before closing. `answer` events carry the exact shape GET /answers/:id returns; a `heartbeat` event fires every 15s; a terminal `error` event means the client should fall back to polling GET /answers/:id. Re-checks the connecting session every 30s and closes if it is gone or moved tenants. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description The caller's tenant or user is already at its open-SSE-stream cap. */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
    };
  };
  QaController_listAnswers: {
    parameters: {
      query?: {
        /** @description Comma-separated fields to include; `_id` is always returned. */
        select?: string;
        /** @description Number of documents to skip (offset). */
        skip?: number;
        /** @description Maximum number of documents to return. */
        limit?: number;
        /** @description Exact workflow run status to filter by. */
        runStatus?: 'queued' | 'running' | 'completed' | 'failed';
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Paginated answer history for the caller's tenant, most recent first, optionally filtered by runStatus. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
    };
  };
  QaController_getAnswerById: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Server-computed answer envelope. `outcome` is present only once runStatus is completed. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AnswerResponseDto'];
        };
      };
      /** @description Answer does not exist. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
    };
  };
  RetrievalController_search: {
    parameters: {
      query: {
        /** @description Search text run against the hybrid retrieval index. */
        query: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Hybrid retrieval hits for the query, ranked as the store returns them. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
    };
  };
  SourcesController_list: {
    parameters: {
      query?: {
        /** @description Comma-separated fields to include; `_id` is always returned. */
        select?: string;
        /** @description Number of documents to skip (offset). */
        skip?: number;
        /** @description Maximum number of documents to return. */
        limit?: number;
        /** @description Exact lastSyncStatus to filter by — currently only 'failed' is meaningful. Omit to list every source regardless of sync outcome. */
        lastSyncStatus?: string;
        /** @description Filter to sources with this exact tracked value. R4 renders synced ('tracked: true') and inventory-only ('tracked: false') sources as two separately-paged lists, so this cannot be done by partitioning one fetched page client-side. */
        tracked?: boolean;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Paginated sources for the tenant. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
    };
  };
  SourcesController_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateSourceRequestDto'];
      };
    };
    responses: {
      /** @description The newly created source. */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      /** @description Caller does not hold the admin role required to create or reconfigure a source. */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      /** @description A source with this name already exists for this tenant. */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
    };
  };
  SourcesController_getById: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The requested source, with per-file sync state. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SourceWithFileStatesResponseDto'];
        };
      };
      /** @description Source does not exist for this tenant. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
    };
  };
  SourcesController_update: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateSourceRequestDto'];
      };
    };
    responses: {
      /** @description The requested source. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      /** @description Caller does not hold the admin role required to create or reconfigure a source. */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      /** @description Source does not exist for this tenant. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
    };
  };
  SourcesController_requestSync: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The sync workflow run for this source — newly started, or the already-running one this request deduplicated against. */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      /** @description Source does not exist for this tenant. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
    };
  };
  SourcesController_getClassDrift: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description How many documents from this source still carry a superseded sourceClass. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      /** @description Source does not exist for this tenant. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
    };
  };
  SourcesController_applyClassDrift: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The result of applying this source's current sourceClass to every document that still carried the previous one. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      /** @description Caller does not hold the admin role required to create or reconfigure a source. */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      /** @description Source does not exist for this tenant. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
    };
  };
  AuditEventsController_list: {
    parameters: {
      query?: {
        /** @description Comma-separated fields to include; `_id` is always returned. */
        select?: string;
        /** @description Number of documents to skip (offset). */
        skip?: number;
        /** @description Maximum number of documents to return. */
        limit?: number;
        /** @description Exact audit action to filter by. */
        action?: string;
        /** @description Exact subject entity type to filter by. */
        entityType?: string;
        /** @description Exact subject entity id to filter by. */
        entityId?: string;
        /** @description Exact origin to filter by: 'mcp' for an AI client holding a PAT, 'api' otherwise. */
        origin?: 'api' | 'mcp';
        /** @description Exact refusal reason to filter by, matching mcp.tool_call.refused rows. */
        refusalReason?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Paginated audit log, most recent first, optionally filtered. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      /** @description Caller does not hold the admin role required to read the audit log. */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
    };
  };
  ApiKeysController_list: {
    parameters: {
      query?: {
        /** @description Comma-separated fields to include; `_id` is always returned. */
        select?: string;
        /** @description Number of documents to skip (offset). */
        skip?: number;
        /** @description Maximum number of documents to return. */
        limit?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The caller's own API keys. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
    };
  };
  ApiKeysController_mint: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateApiKeyRequestDto'];
      };
    };
    responses: {
      /** @description The newly minted key, including its plaintext token — shown exactly once. */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      /** @description The caller already has the maximum number of active API keys. */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
    };
  };
  ApiKeysController_revoke: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The key was revoked. */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description API key does not exist for this user. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
    };
  };
}
