import type { CreateIndexesOptions, Db, IndexDirection, SearchIndexDescription } from 'mongodb';
import { buildSeedMeasureRows } from '../src/features/evidence/measures/measure-seed';
import {
  createSearchIndexesWhenReady,
  waitForSearchIndexReady,
} from '../src/features/evidence/retrieval/search-index-readiness.util';

// Exported for `search-indexes.integration-spec.ts` and `mongo-hybrid.store.integration-spec.ts`,
// which assert against the exact collection/index names this migration creates rather than
// duplicating them.
export const EVIDENCE_CHUNKS_COLLECTION = 'evidence_chunks';
export const SEARCH_INDEX = 'evidence_chunks_search';
export const VECTOR_INDEX = 'evidence_chunks_vector';

const TENANTS_COLLECTION = 'tenants';
const DEFAULT_TENANT_ID = 'default';

/** 30 days: `TenantSpendService` only ever reads or writes the current day's window, so this
 * retention bounds the collection's size against forever-accumulating rows while still leaving a
 * month of spend history available for the tenant an operator is debugging a budget complaint for. */
const MODEL_SPEND_WINDOW_TTL_SECONDS = 30 * 24 * 60 * 60;

const DEFAULT_EMBEDDING_DIMENSIONS = 1024;

/**
 * Migrations run outside Nest's DI, so `TypedConfigService` is unavailable and
 * `environment.config.ts`'s "process.env read in exactly one file" rule (`CLAUDE.md` § Coding
 * Rules) cannot be honoured literally — this is the documented exception. Reading
 * `EMBEDDING_DIMENSIONS` directly, rather than hardcoding a width, is what keeps the vector
 * index's `numDimensions` from drifting out of sync with the selected embedding provider: a
 * mismatched dimension produces an index that builds successfully and then never matches
 * anything, with no error anywhere (`VectorIndexDimensionGuard` is the boot-time check that
 * catches this once the app starts; this function is what the index itself is built from).
 * Default mirrors `environmentSchema`'s `EMBEDDING_DIMENSIONS`
 * (`src/config/environment/environment.config.ts`) so an unset var behaves identically here and in
 * the app; the legal-value set is any positive integer, not a Voyage-only Matryoshka list, since
 * `EMBEDDING_DIMENSIONS` also has to fit a self-hosted or third-party model's native width.
 */
export function resolveVectorDimensions(): number {
  const raw = process.env.EMBEDDING_DIMENSIONS;
  if (raw === undefined || raw.trim() === '') {
    return DEFAULT_EMBEDDING_DIMENSIONS;
  }

  const parsed = Number(raw);
  if (!Number.isInteger(parsed) || parsed < 1) {
    throw new Error(`EMBEDDING_DIMENSIONS must be a positive integer, got "${raw}"`);
  }

  return parsed;
}

interface IndexSpec {
  readonly collection: string;
  readonly keys: Readonly<Record<string, IndexDirection>>;
  readonly options: CreateIndexesOptions;
}

/**
 * Every non-`_id` index the deployed database carries. Names, key patterns and options are
 * byte-identical to the matching `@Schema`/`SchemaFactory` index declarations under
 * `src/database/schemas/` wherever a schema declares one: this table builds them in a deployed
 * database where `autoIndex` is off (`src/config/mongo.config.ts`), the schema declaration is what
 * `Model.syncIndexes()` builds for the test lane that never runs migrations, and MongoDB refuses a
 * second index on an already-carried key pattern under a different name.
 *
 * `tenantId` leads almost every compound index because it is the equality field every real query
 * scopes by first; `createdAt: -1` follows it wherever the access pattern is a newest-first
 * listing.
 *
 * Creating an index also creates its collection, so this table is what brings all eighteen
 * collections into existence.
 */
const INDEXES: readonly IndexSpec[] = [
  // The Mongoose schema also declares `unique` on `email`, but that only materialises when
  // autoIndex is on — which it must not be in production, where index builds belong in a reviewed
  // migration rather than in application boot.
  {
    collection: 'users',
    keys: { email: 1 },
    options: { unique: true, name: 'users_email_unique' },
  },
  // Backs `UsersService.list`'s tenant-scoped, newest-first membership listing — same shape as
  // `invitations_tenantId_createdAt` below.
  {
    collection: 'users',
    keys: { tenantId: 1, createdAt: -1 },
    options: { name: 'users_tenantId_createdAt' },
  },
  // Backs `ListUsersRequestDto`'s `email` sort field — the tenant's membership listing defaults
  // to it (`DEFAULT_USER_SORT_FIELD`), not `createdAt`.
  {
    collection: 'users',
    keys: { tenantId: 1, email: 1 },
    options: { name: 'users_tenantId_email' },
  },

  // `Tenant.tenantId` is opaque and hand-generated by `AuthService.register`, not a Mongo `_id`,
  // so nothing but this index stops a collision in the registry every other collection's
  // `tenantId` points at.
  {
    collection: TENANTS_COLLECTION,
    keys: { tenantId: 1 },
    options: { name: 'tenants_tenantId_unique', unique: true },
  },

  // `api_keys_tokenHash_unique` is the verification lookup path `ApiKeysService.verify` relies on
  // — a duplicate hash would mean two different tokens hash to the same digest, which must never
  // be insertable. `revokedAt` in the third index lets `assertUnderActiveKeyCap` skip revoked rows
  // at the index level rather than filtering them out afterwards.
  {
    collection: 'api_keys',
    keys: { tokenHash: 1 },
    options: { unique: true, name: 'api_keys_tokenHash_unique' },
  },
  {
    collection: 'api_keys',
    keys: { tenantId: 1, userId: 1, createdAt: -1 },
    options: { name: 'api_keys_tenantId_userId_createdAt' },
  },
  {
    collection: 'api_keys',
    keys: { tenantId: 1, userId: 1, revokedAt: 1 },
    options: { name: 'api_keys_tenantId_userId_revokedAt' },
  },
  // Backs `GET /api-keys?sort=name|lastUsedAt|expiresAt` — `list`'s filter always includes
  // `userId` alongside `tenantId`, so each carries the same two-field prefix as the `createdAt`
  // index above rather than a bare `{tenantId, ...}` pair.
  {
    collection: 'api_keys',
    keys: { tenantId: 1, userId: 1, name: 1 },
    options: { name: 'api_keys_tenantId_userId_name' },
  },
  {
    collection: 'api_keys',
    keys: { tenantId: 1, userId: 1, lastUsedAt: 1 },
    options: { name: 'api_keys_tenantId_userId_lastUsedAt' },
  },
  {
    collection: 'api_keys',
    keys: { tenantId: 1, userId: 1, expiresAt: 1 },
    options: { name: 'api_keys_tenantId_userId_expiresAt' },
  },

  // `invitations_expiresAt_ttl` uses `expireAfterSeconds: 0`, which reads `expiresAt` as an
  // absolute deletion time rather than an offset to add to it — Mongo removes a row the moment its
  // clock passes the value already stored there, redeemed or not. The durable record of who
  // accepted an invitation lives in `audit_events`, so the invitation document is disposable token
  // state once its window closes.
  {
    collection: 'invitations',
    keys: { tokenHash: 1 },
    options: { unique: true, name: 'invitations_tokenHash_unique' },
  },
  {
    collection: 'invitations',
    keys: { tenantId: 1, createdAt: -1 },
    options: { name: 'invitations_tenantId_createdAt' },
  },
  {
    collection: 'invitations',
    keys: { expiresAt: 1 },
    options: { name: 'invitations_expiresAt_ttl', expireAfterSeconds: 0 },
  },
  // Backs `GET /invitations?sort=email|expiresAt|role`, the three allowlisted sort fields with no
  // existing `{tenantId, ...}` prefix to ride — the TTL index above is keyed on bare `expiresAt`
  // (no `tenantId` prefix, by design), so it cannot serve a tenant-scoped sort.
  {
    collection: 'invitations',
    keys: { tenantId: 1, email: 1 },
    options: { name: 'invitations_tenantId_email' },
  },
  {
    collection: 'invitations',
    keys: { tenantId: 1, expiresAt: 1 },
    options: { name: 'invitations_tenantId_expiresAt' },
  },
  {
    collection: 'invitations',
    keys: { tenantId: 1, role: 1 },
    options: { name: 'invitations_tenantId_role' },
  },

  // `TenantSpendService.reserve` upserts a window keyed by `(tenantId, windowStart)` and then
  // conditionally increments it; the unique index makes that key collision-free under concurrent
  // first-call upserts for the same tenant and day. The TTL expires rows off `createdAt` (stamped
  // by the schema's `timestamps: true`), not `windowStart`, so a window created near the end of one
  // day and touched again early the next expires on a fixed clock rather than resetting every time
  // it is read.
  {
    collection: 'model_spend_windows',
    keys: { tenantId: 1, windowStart: 1 },
    options: { name: 'model_spend_windows_tenantId_windowStart_unique', unique: true },
  },
  {
    collection: 'model_spend_windows',
    keys: { createdAt: 1 },
    options: {
      name: 'model_spend_windows_createdAt_ttl',
      expireAfterSeconds: MODEL_SPEND_WINDOW_TTL_SECONDS,
    },
  },

  // `documents_emailOrigin_part_unique` makes email-attachment unwrapping idempotent:
  // `(tenantId, emailOrigin.parentVersionId, emailOrigin.partIndex)` identifies one attachment of
  // one message, so a unique index over it refuses a second at-least-once ingest attempt's insert
  // rather than minting a duplicate document.
  //
  // FAILURE DIRECTION: CLOSED. A duplicate-key error on this index is a signal the caller reads as
  // "another attempt already created this attachment", never a reason to write the row anyway.
  //
  // Partial on `emailOrigin.parentVersionId` existing, because every uploaded and synced document
  // lacks `emailOrigin` entirely and a non-partial unique index would collapse all of them onto one
  // `(tenantId, null, null)` key.
  {
    collection: 'documents',
    keys: { tenantId: 1, createdAt: -1 },
    options: { name: 'documents_tenantId_createdAt' },
  },
  {
    collection: 'documents',
    keys: { tenantId: 1, sourceId: 1 },
    options: { name: 'documents_tenantId_sourceId' },
  },
  {
    collection: 'documents',
    keys: { tenantId: 1, 'emailOrigin.parentVersionId': 1, 'emailOrigin.partIndex': 1 },
    options: {
      name: 'documents_emailOrigin_part_unique',
      unique: true,
      partialFilterExpression: { 'emailOrigin.parentVersionId': { $exists: true } },
    },
  },
  // Not unique, unlike the index above: a converged attachment forgets its old location and
  // grows a new one elsewhere, so two locations can carry the same `emailOrigin` part mid-transition.
  {
    collection: 'documents',
    keys: {
      tenantId: 1,
      'locations.emailOrigin.parentVersionId': 1,
      'locations.emailOrigin.partIndex': 1,
    },
    options: {
      name: 'documents_locations_emailOrigin_part',
      partialFilterExpression: { 'locations.emailOrigin.parentVersionId': { $exists: true } },
    },
  },
  // Back `ListDocumentsRequestDto`'s `title`/`sourceKind` sort fields the same way
  // `documents_tenantId_createdAt` above backs its default.
  {
    collection: 'documents',
    keys: { tenantId: 1, title: 1 },
    options: { name: 'documents_tenantId_title' },
  },
  {
    collection: 'documents',
    keys: { tenantId: 1, sourceKind: 1 },
    options: { name: 'documents_tenantId_sourceKind' },
  },

  // The two unique `documentId`-scoped indexes are the defense-in-depth backstop for concurrent
  // writers racing `DocumentsService`'s application-layer checks: one version per (document,
  // sha256) is `DocumentVersion`'s content-addressing invariant, and one version per (document,
  // versionNumber) stops two concurrent uploads taking the same version number.
  //
  // `document_versions_ingestionStatus_updatedAt` deliberately does not lead with `tenantId`:
  // `IngestionService.reconcileStaleAttempts` sweeps abandoned mid-ingest versions across every
  // tenant at once, so it constrains `ingestionStatus` and `updatedAt` only.
  {
    collection: 'document_versions',
    keys: { documentId: 1, sha256: 1 },
    options: { unique: true, name: 'document_versions_documentId_sha256_unique' },
  },
  {
    collection: 'document_versions',
    keys: { documentId: 1, versionNumber: 1 },
    options: { unique: true, name: 'document_versions_documentId_versionNumber_unique' },
  },
  // Tenant-wide, not document-scoped like the two indexes above: it backs
  // `DocumentsService.uploadVersion`'s dedupe lookup, under the invariant that one sha256
  // identifies exactly one `DocumentVersion` per tenant. Strictly narrower than
  // `document_versions_documentId_sha256_unique`, which stays for the same reasoning as every
  // other index pair in this file — the schema declares both, so both are built here.
  {
    collection: 'document_versions',
    keys: { tenantId: 1, sha256: 1 },
    options: { unique: true, name: 'document_versions_tenantId_sha256_unique' },
  },
  {
    collection: 'document_versions',
    keys: { tenantId: 1, documentId: 1, versionNumber: 1 },
    options: { name: 'document_versions_tenantId_documentId_versionNumber' },
  },
  {
    collection: 'document_versions',
    keys: { tenantId: 1, ingestionStatus: 1 },
    options: { name: 'document_versions_tenantId_ingestionStatus' },
  },
  {
    collection: 'document_versions',
    keys: { tenantId: 1, withdrawnAt: 1 },
    options: {
      name: 'document_versions_tenantId_withdrawnAt',
      partialFilterExpression: { withdrawnAt: { $exists: true } },
    },
  },
  {
    collection: 'document_versions',
    keys: { ingestionStatus: 1, updatedAt: 1 },
    options: {
      name: 'document_versions_ingestionStatus_updatedAt',
      partialFilterExpression: { ingestionStatus: 'pending' },
    },
  },

  // Backs `GET /documents/versions/:versionId/chunks`. The lexical and vector indexes this
  // collection also carries are Atlas Search definitions, created separately in `up()`.
  {
    collection: EVIDENCE_CHUNKS_COLLECTION,
    keys: { tenantId: 1, documentVersionId: 1 },
    options: { name: 'evidence_chunks_tenantId_documentVersionId' },
  },

  // `extracted_facts_documentVersionId` backs `FactsService.extractFacts`'s idempotency check and
  // its partial-insert rollback. `extracted_facts_tenantId_chunkId` covers both
  // `FactsService.findCellFacts` and the touched-facts lookup inside
  // `ConflictsService.findConflictedFactGroupsForChunks` — `tenantId` first because it is always an
  // equality match while `chunkId` is an `$in`. `extracted_facts_tenantId_groupKeyNormalized` backs
  // the fact query in `ConflictsService.scanForConflicts`'s incremental path, scoped to the touched
  // groups.
  {
    collection: 'extracted_facts',
    keys: { documentVersionId: 1 },
    options: { name: 'extracted_facts_documentVersionId' },
  },
  {
    collection: 'extracted_facts',
    keys: { tenantId: 1, chunkId: 1 },
    options: { name: 'extracted_facts_tenantId_chunkId' },
  },
  {
    collection: 'extracted_facts',
    keys: { tenantId: 1, groupKeyNormalized: 1 },
    options: { name: 'extracted_facts_tenantId_groupKeyNormalized' },
  },
  // `extracted_facts_tenantId_measureId` backs the fact lookup `MeasuresService.confirm`'s rescan
  // runs to flip `measureStatus` and load `factKey`s for the measure just confirmed.
  // `extracted_facts_tenantId_measureStatus_groupKeyNormalized` backs every consumer that must
  // exclude proposed-measure facts by group (`ConflictsService.scanForConflicts`,
  // `FactsService.findCellFacts`/`findFactsForChunks`, `LedgerService.listCells`/`resolveValue`).
  {
    collection: 'extracted_facts',
    keys: { tenantId: 1, measureId: 1 },
    options: { name: 'extracted_facts_tenantId_measureId' },
  },
  {
    collection: 'extracted_facts',
    keys: { tenantId: 1, measureStatus: 1, groupKeyNormalized: 1 },
    options: { name: 'extracted_facts_tenantId_measureStatus_groupKeyNormalized' },
  },

  // `conflicts_tenantId_status_factIds` puts the multikey `factIds` array last, per Mongo's
  // single-multikey-field-per-compound-index rule, after the two equality fields.
  //
  // `conflicts_tenantId_status_groupKeyNormalized` and
  // `conflicts_tenantId_groupKeyNormalized_open_unique` cover the same key pattern deliberately:
  // the plain one serves `ConflictsService.scanForConflicts`'s open-conflict lookup at any status,
  // the unique one is scoped by `partialFilterExpression` to `status: 'open'` and closes
  // `ConflictsService.detectAndPersist`'s read-then-insert race. Uniqueness holds only among `open`
  // rows because the idempotency design allows more than one `resolved`/`dismissed` row per group —
  // a later, genuinely new disagreement gets its own row.
  //
  // FAILURE DIRECTION: CLOSED. The losing writer of that race gets a driver-level duplicate-key
  // error, which surfaces as an activity failure; the Temporal workflow's activity retry re-runs
  // the scan, which then finds the group's `open` conflict and grows it instead of inserting again.
  {
    collection: 'conflicts',
    keys: { tenantId: 1, status: 1, factIds: 1 },
    options: { name: 'conflicts_tenantId_status_factIds' },
  },
  {
    collection: 'conflicts',
    keys: { tenantId: 1, status: 1, groupKeyNormalized: 1 },
    options: { name: 'conflicts_tenantId_status_groupKeyNormalized' },
  },
  {
    collection: 'conflicts',
    keys: { tenantId: 1, status: 1, groupKeyNormalized: 1 },
    options: {
      name: 'conflicts_tenantId_groupKeyNormalized_open_unique',
      unique: true,
      partialFilterExpression: { status: 'open' },
    },
  },
  // Backs `ConflictsService.list`'s unfiltered, tenant-scoped, newest-first default — the three
  // `{tenantId, status, ...}` indexes above only serve a query that also equality-filters on
  // `status`, which the unfiltered first page does not.
  {
    collection: 'conflicts',
    keys: { tenantId: 1, createdAt: -1 },
    options: { name: 'conflicts_tenantId_createdAt' },
  },

  // Backs the pending-inbox query: "every pending approval for tenant X, oldest first".
  {
    collection: 'approvals',
    keys: { tenantId: 1, state: 1, createdAt: 1 },
    options: { name: 'approvals_tenantId_state_createdAt' },
  },
  // Every real query already filters by `{tenantId, state}` (`ListApprovalsRequestDto.state`
  // defaults to `'pending'`), which the index above already serves. This one backs a query that
  // scopes by `tenantId` and sorts by `createdAt` alone, for a caller that queries without a
  // state filter.
  {
    collection: 'approvals',
    keys: { tenantId: 1, createdAt: -1 },
    options: { name: 'approvals_tenantId_createdAt' },
  },
  // Backs `GET /approvals?sort=decidedAt` — the one allowlisted sort field with no existing
  // `{tenantId, ...}` prefix to ride.
  {
    collection: 'approvals',
    keys: { tenantId: 1, decidedAt: 1 },
    options: { name: 'approvals_tenantId_decidedAt' },
  },

  // Tenant-wide newest-first feeds.
  {
    collection: 'answers',
    keys: { tenantId: 1, createdAt: -1 },
    options: { name: 'answers_tenantId_createdAt' },
  },
  // Backs `GET /answers?sort=runStatus|claimCoverage`, the two allowlisted sort fields with no
  // existing `{tenantId, ...}` prefix to ride.
  {
    collection: 'answers',
    keys: { tenantId: 1, runStatus: 1 },
    options: { name: 'answers_tenantId_runStatus' },
  },
  {
    collection: 'answers',
    keys: { tenantId: 1, claimCoverage: 1 },
    options: { name: 'answers_tenantId_claimCoverage' },
  },

  // Backs `GET /verifications`'s tenant-wide newest-first default listing and its
  // `?requestedByKind=` filter.
  {
    collection: 'verifications',
    keys: { tenantId: 1, createdAt: -1 },
    options: { name: 'verifications_tenantId_createdAt' },
  },
  {
    collection: 'verifications',
    keys: { tenantId: 1, 'requestedBy.kind': 1, createdAt: -1 },
    options: { name: 'verifications_tenantId_requestedByKind_createdAt' },
  },
  {
    collection: 'workflow_runs',
    keys: { tenantId: 1, createdAt: -1 },
    options: { name: 'workflow_runs_tenantId_createdAt' },
  },
  // Backs `GET /workflow-runs?sort=status|workflowType`, the two allowlisted sort fields with no
  // existing `{tenantId, ...}` prefix to ride.
  {
    collection: 'workflow_runs',
    keys: { tenantId: 1, status: 1 },
    options: { name: 'workflow_runs_tenantId_status' },
  },
  {
    collection: 'workflow_runs',
    keys: { tenantId: 1, workflowType: 1 },
    options: { name: 'workflow_runs_tenantId_workflowType' },
  },
  {
    collection: 'audit_events',
    keys: { tenantId: 1, createdAt: -1 },
    options: { name: 'audit_events_tenantId_createdAt' },
  },
  // Backs `GET /audit-events?sort=action|origin`, the two allowlisted sort fields (besides
  // `createdAt`, already served above) with no existing `{tenantId, ...}` prefix to ride.
  {
    collection: 'audit_events',
    keys: { tenantId: 1, action: 1 },
    options: { name: 'audit_events_tenantId_action' },
  },
  {
    collection: 'audit_events',
    keys: { tenantId: 1, origin: 1 },
    options: { name: 'audit_events_tenantId_origin' },
  },

  // The unique `{tenantId, name}` index is the backstop for a `Source` name collision within a
  // tenant; `SourcesService` maps its duplicate-key error onto a 409.
  {
    collection: 'sources',
    keys: { tenantId: 1, createdAt: -1 },
    options: { name: 'sources_tenantId_createdAt' },
  },
  {
    collection: 'sources',
    keys: { tenantId: 1, name: 1 },
    options: { unique: true, name: 'sources_tenantId_name_unique' },
  },
  // Backs `GET /sources?sort=owner|lastSyncAt`, the two allowlisted sort fields with no existing
  // `{tenantId, ...}` prefix to ride — `name` rides the unique index above, `createdAt` rides
  // the index above it.
  {
    collection: 'sources',
    keys: { tenantId: 1, owner: 1 },
    options: { name: 'sources_tenantId_owner' },
  },
  {
    collection: 'sources',
    keys: { tenantId: 1, lastSyncAt: 1 },
    options: { name: 'sources_tenantId_lastSyncAt' },
  },

  // Two canonical rows for the same normalised name within one tenant is a data error, not a
  // merge, so the canonical-name index is unique. The alias index is not: the same alias appearing
  // under two different canonical rows within a tenant is exactly the ambiguity a human needs to
  // resolve, not something an index should silently prevent.
  {
    collection: 'canonical_entities',
    keys: { tenantId: 1, canonicalNameNormalized: 1 },
    options: { unique: true, name: 'canonical_entities_tenantId_canonicalNameNormalized_unique' },
  },
  {
    collection: 'canonical_entities',
    keys: { tenantId: 1, aliasesNormalized: 1 },
    options: { name: 'canonical_entities_tenantId_aliasesNormalized' },
  },
  // Backs the registry's unfiltered, tenant-scoped, newest-first default listing
  // (`CanonicalEntityService.listForTenant`).
  {
    collection: 'canonical_entities',
    keys: { tenantId: 1, createdAt: -1 },
    options: { name: 'canonical_entities_tenantId_createdAt' },
  },

  // Identical keys, options and names to `MeasureSchema`'s own declarations
  // (`measure.schema.ts`) — see that schema's doc comment on the pair for why both exist.
  {
    collection: 'measures',
    keys: { tenantId: 1, slug: 1 },
    options: { unique: true, name: 'measures_tenantId_slug_unique' },
  },
  {
    collection: 'measures',
    keys: { tenantId: 1, status: 1, createdAt: -1 },
    options: { name: 'measures_tenantId_status_createdAt' },
  },
];

/** Every collection this migration creates, derived from the index table so `down()` drops exactly
 * what `up()` builds. */
const COLLECTIONS: readonly string[] = [...new Set(INDEXES.map((index) => index.collection))];

/**
 * Lexical index over chunk text plus the reference fields a retrieval query must pre-filter by.
 * `dynamic: false` with an explicit field list keeps `tenantId`/`documentId`/`documentVersionId`
 * out of full-text analysis — they are exact-match filter fields (`token`/`objectId`), not
 * searchable text, so a `$search` compound `filter` clause can match them precisely.
 */
const searchIndex: SearchIndexDescription = {
  name: SEARCH_INDEX,
  type: 'search',
  definition: {
    mappings: {
      dynamic: false,
      fields: {
        text: { type: 'string' },
        tenantId: { type: 'token' },
        documentId: { type: 'objectId' },
        documentVersionId: { type: 'objectId' },
      },
    },
  },
};

/**
 * `similarity: 'cosine'` over `dotProduct` is a correctness choice, not a default. `dotProduct` is
 * only equivalent to cosine similarity when every stored vector is unit-length, and nothing in
 * `VoyageEmbeddingProvider` (`src/providers/embedding/voyage-embedding.provider.ts`) requests or
 * asserts normalization from the Voyage API. A `dotProduct` index over non-normalized vectors still
 * returns a ranked list, just the wrong ranking — an invisible failure. `cosine` is correct
 * regardless of vector magnitude.
 *
 * `tenantId` is declared a `filter` field (not indexed in `fields` as a vector) so
 * `$vectorSearch`'s `filter` clause can pre-filter candidates by tenant before the ANN search runs,
 * rather than filtering the result set after.
 *
 * Built as a function, not a module-level constant, so `resolveVectorDimensions()` — and the error
 * it can throw on an invalid `EMBEDDING_DIMENSIONS` — only runs during `up()`. Evaluating it at module
 * load would also run it for `down()` and `migrate-mongo status`, where a bad vector width is
 * irrelevant to the operation being performed.
 */
function buildVectorIndex(): SearchIndexDescription {
  return {
    name: VECTOR_INDEX,
    type: 'vectorSearch',
    definition: {
      fields: [
        {
          type: 'vector',
          path: 'embedding',
          numDimensions: resolveVectorDimensions(),
          similarity: 'cosine',
        },
        {
          type: 'filter',
          path: 'tenantId',
        },
      ],
    },
  };
}

/**
 * Builds the whole schema from an empty database: every collection, every index, the Atlas Search
 * and Vector Search definitions on `evidence_chunks`, and the registry row for the default tenant.
 */
export const up = async (db: Db): Promise<void> => {
  for (const { collection, keys, options } of INDEXES) {
    await db.collection(collection).createIndex(keys, options);
  }

  // The registry row every account created without an explicit tenant backs onto. An upsert rather
  // than a bare insert, so re-running this against a database that already has the row is a no-op
  // instead of a duplicate-key error.
  await db
    .collection(TENANTS_COLLECTION)
    .updateOne(
      { tenantId: DEFAULT_TENANT_ID },
      { $setOnInsert: { tenantId: DEFAULT_TENANT_ID, name: 'Default tenant' } },
      { upsert: true },
    );

  // Runs for every registry row, not just the default tenant just upserted above: a real
  // deployment carries other tenants by the time this migration reaches it. `$setOnInsert` with
  // `upsert: true` makes each row a no-op on re-run — a tenant that already carries a slug (seeded
  // by `AuthService.register` at its own birth, or by an earlier run of this migration) is left
  // untouched rather than overwritten.
  const tenants = await db
    .collection<{ tenantId: string }>(TENANTS_COLLECTION)
    .find({}, { projection: { tenantId: 1 } })
    .toArray();
  for (const tenant of tenants) {
    for (const row of buildSeedMeasureRows(tenant.tenantId)) {
      await db
        .collection('measures')
        .updateOne(
          { tenantId: row.tenantId, slug: row.slug },
          { $setOnInsert: row },
          { upsert: true },
        );
    }
  }

  // Waits for the Search Index Management service rather than assuming it is up: `mongod` accepts
  // every other command in this migration seconds before it can reach `mongot`, so on the first
  // boot of a fresh volume the index build is the one step that can arrive too early.
  await createSearchIndexesWhenReady(db, EVIDENCE_CHUNKS_COLLECTION, [
    searchIndex,
    buildVectorIndex(),
  ]);

  // Both builds run concurrently on the server; wait for each so `up()` never reports success while
  // an index is still building — a migration that "succeeds" early hands the next reader a store
  // that silently returns nothing until the build catches up.
  await waitForSearchIndexReady(db, EVIDENCE_CHUNKS_COLLECTION, SEARCH_INDEX);
  await waitForSearchIndexReady(db, EVIDENCE_CHUNKS_COLLECTION, VECTOR_INDEX);
};

/**
 * `dropCollection` on a collection that was never created in this environment throws "ns not found"
 * (driver error code 26) — tolerated rather than checked for first, since a check-then-drop is
 * itself a race against a concurrent migration run.
 */
async function dropIfExists(db: Db, collectionName: string): Promise<void> {
  try {
    await db.collection(collectionName).drop();
  } catch (error) {
    if ((error as { code?: number }).code !== 26) {
      throw error;
    }
  }
}

/**
 * Drops all eighteen collections `up()` creates, and with them every index, Atlas Search definition,
 * seeded row and any application data written since. This is destructive and total: reverting a
 * baseline means returning the database to empty, not preserving what was stored on top of the
 * schema it built.
 */
export const down = async (db: Db): Promise<void> => {
  for (const collection of COLLECTIONS) {
    await dropIfExists(db, collection);
  }
};
