import type { CreateIndexesOptions, Db, IndexDirection, SearchIndexDescription } from 'mongodb';
import { waitForSearchIndexReady } from '../src/features/evidence/retrieval/search-index-readiness.util';

// Exported for `search-indexes.integration-spec.ts` and `mongo-hybrid.store.integration-spec.ts`,
// which assert against the exact collection/index names this migration creates rather than
// duplicating them.
export const EVIDENCE_CHUNKS_COLLECTION = 'evidence_chunks';
export const SEARCH_INDEX = 'evidence_chunks_search';
export const VECTOR_INDEX = 'evidence_chunks_vector';

const TENANTS_COLLECTION = 'tenants';
const DEFAULT_TENANT_ID = 'default';

/** 30 days: `TenantSpendService` only ever reads or writes the current day's window, so this
 * retention bounds the collection's size against forever-accumulating rows while still leaving a
 * month of spend history available for the tenant an operator is debugging a budget complaint for. */
const MODEL_SPEND_WINDOW_TTL_SECONDS = 30 * 24 * 60 * 60;

const ALLOWED_VOYAGE_DIMENSIONS = [256, 512, 1024, 2048] as const;
const DEFAULT_VOYAGE_DIMENSIONS: (typeof ALLOWED_VOYAGE_DIMENSIONS)[number] = 1024;

function isAllowedDimension(n: number): n is (typeof ALLOWED_VOYAGE_DIMENSIONS)[number] {
  return (ALLOWED_VOYAGE_DIMENSIONS as readonly number[]).includes(n);
}

/**
 * Migrations run outside Nest's DI, so `TypedConfigService` is unavailable and
 * `environment.config.ts`'s "process.env read in exactly one file" rule (`CLAUDE.md` § Coding
 * Rules) cannot be honoured literally — this is the documented exception. Reading
 * `VOYAGE_DIMENSIONS` directly, rather than hardcoding a width, is what keeps the vector index's
 * `numDimensions` from drifting out of sync with the embedding model: a mismatched dimension
 * produces an index that builds successfully and then never matches anything, with no error
 * anywhere. Default and legal-value set mirror `environmentSchema`'s `VOYAGE_DIMENSIONS`
 * (`src/config/environment/environment.config.ts`) so an unset var behaves identically here and in
 * the app.
 */
export function resolveVectorDimensions(): number {
  const raw = process.env.VOYAGE_DIMENSIONS;
  if (raw === undefined || raw.trim() === '') {
    return DEFAULT_VOYAGE_DIMENSIONS;
  }

  const parsed = Number(raw);
  if (!isAllowedDimension(parsed)) {
    throw new Error(
      `VOYAGE_DIMENSIONS must be one of ${ALLOWED_VOYAGE_DIMENSIONS.join(', ')}, got "${raw}"`,
    );
  }

  return parsed;
}

interface IndexSpec {
  readonly collection: string;
  readonly keys: Readonly<Record<string, IndexDirection>>;
  readonly options: CreateIndexesOptions;
}

/**
 * Every non-`_id` index the deployed database carries. Names, key patterns and options are
 * byte-identical to the matching `@Schema`/`SchemaFactory` index declarations under
 * `src/database/schemas/` wherever a schema declares one: this table builds them in a deployed
 * database where `autoIndex` is off (`src/config/mongo.config.ts`), the schema declaration is what
 * `Model.syncIndexes()` builds for the test lane that never runs migrations, and MongoDB refuses a
 * second index on an already-carried key pattern under a different name.
 *
 * `tenantId` leads almost every compound index because it is the equality field every real query
 * scopes by first; `createdAt: -1` follows it wherever the access pattern is a newest-first
 * listing.
 *
 * Creating an index also creates its collection, so this table is what brings all sixteen
 * collections into existence.
 */
const INDEXES: readonly IndexSpec[] = [
  // The Mongoose schema also declares `unique` on `email`, but that only materialises when
  // autoIndex is on — which it must not be in production, where index builds belong in a reviewed
  // migration rather than in application boot.
  {
    collection: 'users',
    keys: { email: 1 },
    options: { unique: true, name: 'users_email_unique' },
  },

  // `Tenant.tenantId` is opaque and hand-generated by `AuthService.register`, not a Mongo `_id`,
  // so nothing but this index stops a collision in the registry every other collection's
  // `tenantId` points at.
  {
    collection: TENANTS_COLLECTION,
    keys: { tenantId: 1 },
    options: { name: 'tenants_tenantId_unique', unique: true },
  },

  // `api_keys_tokenHash_unique` is the verification lookup path `ApiKeysService.verify` relies on
  // — a duplicate hash would mean two different tokens hash to the same digest, which must never
  // be insertable. `revokedAt` in the third index lets `assertUnderActiveKeyCap` skip revoked rows
  // at the index level rather than filtering them out afterwards.
  {
    collection: 'api_keys',
    keys: { tokenHash: 1 },
    options: { unique: true, name: 'api_keys_tokenHash_unique' },
  },
  {
    collection: 'api_keys',
    keys: { tenantId: 1, userId: 1, createdAt: -1 },
    options: { name: 'api_keys_tenantId_userId_createdAt' },
  },
  {
    collection: 'api_keys',
    keys: { tenantId: 1, userId: 1, revokedAt: 1 },
    options: { name: 'api_keys_tenantId_userId_revokedAt' },
  },

  // `invitations_expiresAt_ttl` uses `expireAfterSeconds: 0`, which reads `expiresAt` as an
  // absolute deletion time rather than an offset to add to it — Mongo removes a row the moment its
  // clock passes the value already stored there, redeemed or not. The durable record of who
  // accepted an invitation lives in `audit_events`, so the invitation document is disposable token
  // state once its window closes.
  {
    collection: 'invitations',
    keys: { tokenHash: 1 },
    options: { unique: true, name: 'invitations_tokenHash_unique' },
  },
  {
    collection: 'invitations',
    keys: { tenantId: 1, createdAt: -1 },
    options: { name: 'invitations_tenantId_createdAt' },
  },
  {
    collection: 'invitations',
    keys: { expiresAt: 1 },
    options: { name: 'invitations_expiresAt_ttl', expireAfterSeconds: 0 },
  },

  // `TenantSpendService.reserve` upserts a window keyed by `(tenantId, windowStart)` and then
  // conditionally increments it; the unique index makes that key collision-free under concurrent
  // first-call upserts for the same tenant and day. The TTL expires rows off `createdAt` (stamped
  // by the schema's `timestamps: true`), not `windowStart`, so a window created near the end of one
  // day and touched again early the next expires on a fixed clock rather than resetting every time
  // it is read.
  {
    collection: 'model_spend_windows',
    keys: { tenantId: 1, windowStart: 1 },
    options: { name: 'model_spend_windows_tenantId_windowStart_unique', unique: true },
  },
  {
    collection: 'model_spend_windows',
    keys: { createdAt: 1 },
    options: {
      name: 'model_spend_windows_createdAt_ttl',
      expireAfterSeconds: MODEL_SPEND_WINDOW_TTL_SECONDS,
    },
  },

  // `documents_emailOrigin_part_unique` makes email-attachment unwrapping idempotent:
  // `(tenantId, emailOrigin.parentVersionId, emailOrigin.partIndex)` identifies one attachment of
  // one message, so a unique index over it refuses a second at-least-once ingest attempt's insert
  // rather than minting a duplicate document.
  //
  // FAILURE DIRECTION: CLOSED. A duplicate-key error on this index is a signal the caller reads as
  // "another attempt already created this attachment", never a reason to write the row anyway.
  //
  // Partial on `emailOrigin.parentVersionId` existing, because every uploaded and synced document
  // lacks `emailOrigin` entirely and a non-partial unique index would collapse all of them onto one
  // `(tenantId, null, null)` key.
  {
    collection: 'documents',
    keys: { tenantId: 1, createdAt: -1 },
    options: { name: 'documents_tenantId_createdAt' },
  },
  {
    collection: 'documents',
    keys: { tenantId: 1, sourceId: 1 },
    options: { name: 'documents_tenantId_sourceId' },
  },
  {
    collection: 'documents',
    keys: { tenantId: 1, 'emailOrigin.parentVersionId': 1, 'emailOrigin.partIndex': 1 },
    options: {
      name: 'documents_emailOrigin_part_unique',
      unique: true,
      partialFilterExpression: { 'emailOrigin.parentVersionId': { $exists: true } },
    },
  },

  // The two unique `documentId`-scoped indexes are the defense-in-depth backstop for concurrent
  // writers racing `DocumentsService`'s application-layer checks: one version per (document,
  // sha256) is `DocumentVersion`'s content-addressing invariant, and one version per (document,
  // versionNumber) stops two concurrent uploads taking the same version number.
  //
  // `document_versions_ingestionStatus_updatedAt` deliberately does not lead with `tenantId`:
  // `IngestionService.reconcileStaleAttempts` sweeps abandoned mid-ingest versions across every
  // tenant at once, so it constrains `ingestionStatus` and `updatedAt` only.
  {
    collection: 'document_versions',
    keys: { documentId: 1, sha256: 1 },
    options: { unique: true, name: 'document_versions_documentId_sha256_unique' },
  },
  {
    collection: 'document_versions',
    keys: { documentId: 1, versionNumber: 1 },
    options: { unique: true, name: 'document_versions_documentId_versionNumber_unique' },
  },
  {
    collection: 'document_versions',
    keys: { tenantId: 1, documentId: 1, versionNumber: 1 },
    options: { name: 'document_versions_tenantId_documentId_versionNumber' },
  },
  {
    collection: 'document_versions',
    keys: { tenantId: 1, ingestionStatus: 1 },
    options: { name: 'document_versions_tenantId_ingestionStatus' },
  },
  {
    collection: 'document_versions',
    keys: { tenantId: 1, withdrawnAt: 1 },
    options: {
      name: 'document_versions_tenantId_withdrawnAt',
      partialFilterExpression: { withdrawnAt: { $exists: true } },
    },
  },
  {
    collection: 'document_versions',
    keys: { ingestionStatus: 1, updatedAt: 1 },
    options: {
      name: 'document_versions_ingestionStatus_updatedAt',
      partialFilterExpression: { ingestionStatus: 'pending' },
    },
  },

  // Backs `GET /documents/versions/:versionId/chunks`. The lexical and vector indexes this
  // collection also carries are Atlas Search definitions, created separately in `up()`.
  {
    collection: EVIDENCE_CHUNKS_COLLECTION,
    keys: { tenantId: 1, documentVersionId: 1 },
    options: { name: 'evidence_chunks_tenantId_documentVersionId' },
  },

  // `extracted_facts_documentVersionId` backs `FactsService.extractFacts`'s idempotency check and
  // its partial-insert rollback. `extracted_facts_tenantId_chunkId` covers both
  // `FactsService.findCellFacts` and the touched-facts lookup inside
  // `ConflictsService.findConflictedFactGroupsForChunks` — `tenantId` first because it is always an
  // equality match while `chunkId` is an `$in`. `extracted_facts_tenantId_groupKeyNormalized` backs
  // the fact query in `ConflictsService.scanForConflicts`'s incremental path, scoped to the touched
  // groups.
  {
    collection: 'extracted_facts',
    keys: { documentVersionId: 1 },
    options: { name: 'extracted_facts_documentVersionId' },
  },
  {
    collection: 'extracted_facts',
    keys: { tenantId: 1, chunkId: 1 },
    options: { name: 'extracted_facts_tenantId_chunkId' },
  },
  {
    collection: 'extracted_facts',
    keys: { tenantId: 1, groupKeyNormalized: 1 },
    options: { name: 'extracted_facts_tenantId_groupKeyNormalized' },
  },

  // `conflicts_tenantId_status_factIds` puts the multikey `factIds` array last, per Mongo's
  // single-multikey-field-per-compound-index rule, after the two equality fields.
  //
  // `conflicts_tenantId_status_groupKeyNormalized` and
  // `conflicts_tenantId_groupKeyNormalized_open_unique` cover the same key pattern deliberately:
  // the plain one serves `ConflictsService.scanForConflicts`'s open-conflict lookup at any status,
  // the unique one is scoped by `partialFilterExpression` to `status: 'open'` and closes
  // `ConflictsService.detectAndPersist`'s read-then-insert race. Uniqueness holds only among `open`
  // rows because the idempotency design allows more than one `resolved`/`dismissed` row per group —
  // a later, genuinely new disagreement gets its own row.
  //
  // FAILURE DIRECTION: CLOSED. The losing writer of that race gets a driver-level duplicate-key
  // error, which surfaces as an activity failure; the Temporal workflow's activity retry re-runs
  // the scan, which then finds the group's `open` conflict and grows it instead of inserting again.
  {
    collection: 'conflicts',
    keys: { tenantId: 1, status: 1, factIds: 1 },
    options: { name: 'conflicts_tenantId_status_factIds' },
  },
  {
    collection: 'conflicts',
    keys: { tenantId: 1, status: 1, groupKeyNormalized: 1 },
    options: { name: 'conflicts_tenantId_status_groupKeyNormalized' },
  },
  {
    collection: 'conflicts',
    keys: { tenantId: 1, status: 1, groupKeyNormalized: 1 },
    options: {
      name: 'conflicts_tenantId_groupKeyNormalized_open_unique',
      unique: true,
      partialFilterExpression: { status: 'open' },
    },
  },

  // Backs the pending-inbox query: "every pending approval for tenant X, oldest first".
  {
    collection: 'approvals',
    keys: { tenantId: 1, state: 1, createdAt: 1 },
    options: { name: 'approvals_tenantId_state_createdAt' },
  },

  // Tenant-wide newest-first feeds.
  {
    collection: 'answers',
    keys: { tenantId: 1, createdAt: -1 },
    options: { name: 'answers_tenantId_createdAt' },
  },
  {
    collection: 'workflow_runs',
    keys: { tenantId: 1, createdAt: -1 },
    options: { name: 'workflow_runs_tenantId_createdAt' },
  },
  {
    collection: 'audit_events',
    keys: { tenantId: 1, createdAt: -1 },
    options: { name: 'audit_events_tenantId_createdAt' },
  },

  // The unique `{tenantId, name}` index is the backstop for a `Source` name collision within a
  // tenant; `SourcesService` maps its duplicate-key error onto a 409.
  {
    collection: 'sources',
    keys: { tenantId: 1, createdAt: -1 },
    options: { name: 'sources_tenantId_createdAt' },
  },
  {
    collection: 'sources',
    keys: { tenantId: 1, name: 1 },
    options: { unique: true, name: 'sources_tenantId_name_unique' },
  },

  // Two canonical rows for the same normalised name within one tenant is a data error, not a
  // merge, so the canonical-name index is unique. The alias index is not: the same alias appearing
  // under two different canonical rows within a tenant is exactly the ambiguity a human needs to
  // resolve, not something an index should silently prevent.
  {
    collection: 'canonical_entities',
    keys: { tenantId: 1, canonicalNameNormalized: 1 },
    options: { unique: true, name: 'canonical_entities_tenantId_canonicalNameNormalized_unique' },
  },
  {
    collection: 'canonical_entities',
    keys: { tenantId: 1, aliasesNormalized: 1 },
    options: { name: 'canonical_entities_tenantId_aliasesNormalized' },
  },
];

/** Every collection this migration creates, derived from the index table so `down()` drops exactly
 * what `up()` builds. */
const COLLECTIONS: readonly string[] = [...new Set(INDEXES.map((index) => index.collection))];

/**
 * Lexical index over chunk text plus the reference fields a retrieval query must pre-filter by.
 * `dynamic: false` with an explicit field list keeps `tenantId`/`documentId`/`documentVersionId`
 * out of full-text analysis — they are exact-match filter fields (`token`/`objectId`), not
 * searchable text, so a `$search` compound `filter` clause can match them precisely.
 */
const searchIndex: SearchIndexDescription = {
  name: SEARCH_INDEX,
  type: 'search',
  definition: {
    mappings: {
      dynamic: false,
      fields: {
        text: { type: 'string' },
        tenantId: { type: 'token' },
        documentId: { type: 'objectId' },
        documentVersionId: { type: 'objectId' },
      },
    },
  },
};

/**
 * `similarity: 'cosine'` over `dotProduct` is a correctness choice, not a default. `dotProduct` is
 * only equivalent to cosine similarity when every stored vector is unit-length, and nothing in
 * `VoyageEmbeddingProvider` (`src/providers/embedding/voyage-embedding.provider.ts`) requests or
 * asserts normalization from the Voyage API. A `dotProduct` index over non-normalized vectors still
 * returns a ranked list, just the wrong ranking — an invisible failure. `cosine` is correct
 * regardless of vector magnitude.
 *
 * `tenantId` is declared a `filter` field (not indexed in `fields` as a vector) so
 * `$vectorSearch`'s `filter` clause can pre-filter candidates by tenant before the ANN search runs,
 * rather than filtering the result set after.
 *
 * Built as a function, not a module-level constant, so `resolveVectorDimensions()` — and the error
 * it can throw on an invalid `VOYAGE_DIMENSIONS` — only runs during `up()`. Evaluating it at module
 * load would also run it for `down()` and `migrate-mongo status`, where a bad vector width is
 * irrelevant to the operation being performed.
 */
function buildVectorIndex(): SearchIndexDescription {
  return {
    name: VECTOR_INDEX,
    type: 'vectorSearch',
    definition: {
      fields: [
        {
          type: 'vector',
          path: 'embedding',
          numDimensions: resolveVectorDimensions(),
          similarity: 'cosine',
        },
        {
          type: 'filter',
          path: 'tenantId',
        },
      ],
    },
  };
}

/**
 * Builds the whole schema from an empty database: every collection, every index, the Atlas Search
 * and Vector Search definitions on `evidence_chunks`, and the registry row for the default tenant.
 */
export const up = async (db: Db): Promise<void> => {
  for (const { collection, keys, options } of INDEXES) {
    await db.collection(collection).createIndex(keys, options);
  }

  // The registry row every account created without an explicit tenant backs onto. An upsert rather
  // than a bare insert, so re-running this against a database that already has the row is a no-op
  // instead of a duplicate-key error.
  await db
    .collection(TENANTS_COLLECTION)
    .updateOne(
      { tenantId: DEFAULT_TENANT_ID },
      { $setOnInsert: { tenantId: DEFAULT_TENANT_ID, name: 'Default tenant' } },
      { upsert: true },
    );

  await db
    .collection(EVIDENCE_CHUNKS_COLLECTION)
    .createSearchIndexes([searchIndex, buildVectorIndex()]);

  // Both builds run concurrently on the server; wait for each so `up()` never reports success while
  // an index is still building — a migration that "succeeds" early hands the next reader a store
  // that silently returns nothing until the build catches up.
  await waitForSearchIndexReady(db, EVIDENCE_CHUNKS_COLLECTION, SEARCH_INDEX);
  await waitForSearchIndexReady(db, EVIDENCE_CHUNKS_COLLECTION, VECTOR_INDEX);
};

/**
 * `dropCollection` on a collection that was never created in this environment throws "ns not found"
 * (driver error code 26) — tolerated rather than checked for first, since a check-then-drop is
 * itself a race against a concurrent migration run.
 */
async function dropIfExists(db: Db, collectionName: string): Promise<void> {
  try {
    await db.collection(collectionName).drop();
  } catch (error) {
    if ((error as { code?: number }).code !== 26) {
      throw error;
    }
  }
}

/**
 * Drops all sixteen collections `up()` creates, and with them every index, Atlas Search definition,
 * seeded row and any application data written since. This is destructive and total: reverting a
 * baseline means returning the database to empty, not preserving what was stored on top of the
 * schema it built.
 */
export const down = async (db: Db): Promise<void> => {
  for (const collection of COLLECTIONS) {
    await dropIfExists(db, collection);
  }
};
