import type { Db } from 'mongodb';

const COLLECTION = 'tenants';
const TENANT_ID_INDEX = 'tenants_tenantId_unique';
const DEFAULT_TENANT_ID = 'default';

/**
 * `tenant.schema.ts` introduces the tenant registry that `User.tenantId` (and every other
 * collection's `tenantId`) points at. The unique index enforces the registry's own invariant —
 * `Tenant.tenantId` is opaque and hand-generated by `AuthService.register`, not a Mongo `_id`, so
 * nothing else stops a collision. The upsert backfills a registry row for the demo tenant every
 * pre-existing user already carries (`0010-user-tenancy-and-roles.ts`); it is an upsert rather than
 * a bare insert so re-running this migration against a database that already has the row is a
 * no-op instead of a duplicate-key error.
 */
export const up = async (db: Db): Promise<void> => {
  await db
    .collection(COLLECTION)
    .createIndex({ tenantId: 1 }, { name: TENANT_ID_INDEX, unique: true });

  await db
    .collection(COLLECTION)
    .updateOne(
      { tenantId: DEFAULT_TENANT_ID },
      { $setOnInsert: { tenantId: DEFAULT_TENANT_ID, name: 'Default tenant' } },
      { upsert: true },
    );
};

export const down = async (db: Db): Promise<void> => {
  await db.collection(COLLECTION).dropIndex(TENANT_ID_INDEX);
  await db.collection(COLLECTION).deleteOne({ tenantId: DEFAULT_TENANT_ID });
};
